#pragma once

// clang-format off

enum
{
    JA_ID_FRAME_MAIN_WINDOW = 10001,
    LIST_STACK_LIST,
    // local variables
    PANEL_LOCAL_VARIABLES,
    TREE_LIST_LOCAL_VARIABLES,
    // breakpoints
    PANEL_BREAKPOINTS,
    TREE_LIST_BREAKPOINTS,
    TREE_LIST_BREAKPOINTS_CONTEXT_MENU_GOTO,
    TREE_LIST_BREAKPOINTS_CONTEXT_MENU_DELETE,
    TREE_LIST_BREAKPOINTS_CONTEXT_MENU_ENABLE,
    TREE_LIST_BREAKPOINTS_CONTEXT_MENU_DISABLE,
    TREE_LIST_BREAKPOINTS_CONTEXT_MENU_ENABLE_ALL,
    TREE_LIST_BREAKPOINTS_CONTEXT_MENU_DISABLE_ALL,
    TREE_LIST_BREAKPOINTS_CONTEXT_MENU_DELETE_ALL,
    TREE_LIST_BREAKPOINTS_CONTEXT_MENU_NEW_BREAKPOINT,

    /* Stack Panel*/
    PANEL_STACK,

    /*Session Panel*/
    PANEL_SESSIONS,
    LIST_SESSION,
    TREE_LIST_SESSIONS_OPEN,
    TREE_LIST_SESSIONS_EDIT,
    TREE_LIST_SESSIONS_CLOSE,
    TREE_LIST_SESSIONS_DELETE,
    
    /*Dialogs*/
    DIALOG_NEW_SIMPLE_BREAKPOINT,
    DIALOG_SESSION,

    /* Edit Menu */
    MENU_ITEM_EDIT_GOTO_LINE,
    MENU_ITEM_EDIT_FIND,

    
    /*Help Menu*/
    MENU_ITEM_HELP_ABOUT,
    MENU_ITEM_HELP_SETTINGS,
    /* go to menu*/
    MENU_ITEM_GOTO_SESSIONS,
    MENU_ITEM_GOTO_BREAKPOINTS,
    MENU_ITEM_GOTO_LOCAL_VARIABLES,
    MENU_ITEM_VIEW_SOURCE_SEARCH_FOCUS,
    /*View Menu*/
    MENU_ITEM_VIEW_SESSIONS,
    MENU_ITEM_VIEW_BREAKPOINTS,
    MENU_ITEM_VIEW_STACKS,
    MENU_ITEM_VIEW_LOCAL_VARIABLES,
    MENU_ITEM_VIEW_SOURCE_FILES,

   MENU_SESSION_ID_NEW,
   MENU_SESSION_ID_NEW_EXEC,
   MENU_SESSION_ID_NEW_LOCAL_ATTACH,
   MENU_SESSION_ID_NEW_REMOTE_ATTACH,
   MENU_SESSION_ID_NEW_COREDUMP,
   MENU_SESSION_ID_OPEN,
   MENU_SESSION_ID_CLOSE,
   MENU_SESSION_ID_SAVE,
   //
   MENU_DEBUG_ID_RUN,
   MENU_DEBUG_ID_STEP_IN,
   MENU_DEBUG_ID_STEP_OUT,
   MENU_DEBUG_ID_NEXT,
   MENU_DEBUG_ID_CONTINUE,
   MENU_DEBUG_ID_FINISH,
   MENU_DEBUG_ID_RUN_TO_LINE,
   MENU_DEBUG_ID_INTERRUPT,

   // CODE VIEW
   CODE_VIEW_CONTEXT_MENU_TOGGLE_BREAKPOINT,
   CODE_VIEW_CONTEXT_MENU_RUN_TO_LINE,

};
// clang-format on
