#include "jaeTextEditControl.h"

jaeTextEditControl::jaeTextEditControl(wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size, long style, const wxString &name) /* : wxControl(parent, id, pos, size, style, name)*/ {}

jaeTextEditControl::~jaeTextEditControl() {}

auto jaeTextEditControl::TextReturner(int message, uptr_t wParam) const -> wxCharBuffer {
   int          length = Send(message, wParam, 0);
   wxCharBuffer ba(length);
   Send(message, wParam, (sptr_t)ba.data());

   // Remove extra NULs
   // if (ba.length() > 0 && ba.at(ba.length() - 1) == 0) {
   //      ba.chop(1);
   // }
   return ba;
}

/* ++Autogenerated -- start of section automatically generated from Scintilla.iface */
void jaeTextEditControl::addText(sptr_t length, const char * text) {
    Send(SCI_ADDTEXT, length, (sptr_t)text);
}

void jaeTextEditControl::addStyledText(sptr_t length, const char * c) {
    Send(SCI_ADDSTYLEDTEXT, length, (sptr_t)c);
}

void jaeTextEditControl::insertText(sptr_t pos, const char * text) {
    Send(SCI_INSERTTEXT, pos, (sptr_t)text);
}

void jaeTextEditControl::changeInsertion(sptr_t length, const char * text) {
    Send(SCI_CHANGEINSERTION, length, (sptr_t)text);
}

void jaeTextEditControl::clearAll() {
    Send(SCI_CLEARALL, 0, 0);
}

void jaeTextEditControl::deleteRange(sptr_t start, sptr_t lengthDelete) {
    Send(SCI_DELETERANGE, start, lengthDelete);
}

void jaeTextEditControl::clearDocumentStyle() {
    Send(SCI_CLEARDOCUMENTSTYLE, 0, 0);
}

auto  jaeTextEditControl::length() const -> sptr_t {
    return Send(SCI_GETLENGTH, 0, 0);
}

auto  jaeTextEditControl::charAt(sptr_t pos) const -> sptr_t {
    return Send(SCI_GETCHARAT, pos, 0);
}

auto  jaeTextEditControl::currentPos() const -> sptr_t {
    return Send(SCI_GETCURRENTPOS, 0, 0);
}

auto  jaeTextEditControl::anchor() const -> sptr_t {
    return Send(SCI_GETANCHOR, 0, 0);
}

auto  jaeTextEditControl::styleAt(sptr_t pos) const -> sptr_t {
    return Send(SCI_GETSTYLEAT, pos, 0);
}

void jaeTextEditControl::redo() {
    Send(SCI_REDO, 0, 0);
}

void jaeTextEditControl::setUndoCollection(bool collectUndo) {
    Send(SCI_SETUNDOCOLLECTION, collectUndo, 0);
}

void jaeTextEditControl::selectAll() {
    Send(SCI_SELECTALL, 0, 0);
}

void jaeTextEditControl::setSavePoint() {
    Send(SCI_SETSAVEPOINT, 0, 0);
}

auto  jaeTextEditControl::canRedo() -> bool {
    return Send(SCI_CANREDO, 0, 0);
}

auto  jaeTextEditControl::markerLineFromHandle(sptr_t markerHandle) -> sptr_t {
    return Send(SCI_MARKERLINEFROMHANDLE, markerHandle, 0);
}

void jaeTextEditControl::markerDeleteHandle(sptr_t markerHandle) {
    Send(SCI_MARKERDELETEHANDLE, markerHandle, 0);
}

auto  jaeTextEditControl::markerHandleFromLine(sptr_t line, sptr_t which) -> sptr_t {
    return Send(SCI_MARKERHANDLEFROMLINE, line, which);
}

auto  jaeTextEditControl::markerNumberFromLine(sptr_t line, sptr_t which) -> sptr_t {
    return Send(SCI_MARKERNUMBERFROMLINE, line, which);
}

auto  jaeTextEditControl::undoCollection() const -> bool {
    return Send(SCI_GETUNDOCOLLECTION, 0, 0);
}

auto  jaeTextEditControl::viewWS() const -> sptr_t {
    return Send(SCI_GETVIEWWS, 0, 0);
}

void jaeTextEditControl::setViewWS(sptr_t viewWS) {
    Send(SCI_SETVIEWWS, viewWS, 0);
}

auto  jaeTextEditControl::tabDrawMode() const -> sptr_t {
    return Send(SCI_GETTABDRAWMODE, 0, 0);
}

void jaeTextEditControl::setTabDrawMode(sptr_t tabDrawMode) {
    Send(SCI_SETTABDRAWMODE, tabDrawMode, 0);
}

auto  jaeTextEditControl::positionFromPoint(sptr_t x, sptr_t y) -> sptr_t {
    return Send(SCI_POSITIONFROMPOINT, x, y);
}

auto  jaeTextEditControl::positionFromPointClose(sptr_t x, sptr_t y) -> sptr_t {
    return Send(SCI_POSITIONFROMPOINTCLOSE, x, y);
}

void jaeTextEditControl::gotoLine(sptr_t line) {
    Send(SCI_GOTOLINE, line, 0);
}

void jaeTextEditControl::gotoPos(sptr_t caret) {
    Send(SCI_GOTOPOS, caret, 0);
}

void jaeTextEditControl::setAnchor(sptr_t anchor) {
    Send(SCI_SETANCHOR, anchor, 0);
}

auto  jaeTextEditControl::getCurLine(sptr_t length) -> wxCharBuffer {
    return TextReturner(SCI_GETCURLINE, length);
}

auto  jaeTextEditControl::endStyled() const -> sptr_t {
    return Send(SCI_GETENDSTYLED, 0, 0);
}

void jaeTextEditControl::convertEOLs(sptr_t eolMode) {
    Send(SCI_CONVERTEOLS, eolMode, 0);
}

auto  jaeTextEditControl::eOLMode() const -> sptr_t {
    return Send(SCI_GETEOLMODE, 0, 0);
}

void jaeTextEditControl::setEOLMode(sptr_t eolMode) {
    Send(SCI_SETEOLMODE, eolMode, 0);
}

void jaeTextEditControl::startStyling(sptr_t start, sptr_t unused) {
    Send(SCI_STARTSTYLING, start, unused);
}

void jaeTextEditControl::setStyling(sptr_t length, sptr_t style) {
    Send(SCI_SETSTYLING, length, style);
}

auto  jaeTextEditControl::bufferedDraw() const -> bool {
    return Send(SCI_GETBUFFEREDDRAW, 0, 0);
}

void jaeTextEditControl::setBufferedDraw(bool buffered) {
    Send(SCI_SETBUFFEREDDRAW, buffered, 0);
}

void jaeTextEditControl::setTabWidth(sptr_t tabWidth) {
    Send(SCI_SETTABWIDTH, tabWidth, 0);
}

auto  jaeTextEditControl::tabWidth() const -> sptr_t {
    return Send(SCI_GETTABWIDTH, 0, 0);
}

void jaeTextEditControl::setTabMinimumWidth(sptr_t pixels) {
    Send(SCI_SETTABMINIMUMWIDTH, pixels, 0);
}

auto  jaeTextEditControl::tabMinimumWidth() const -> sptr_t {
    return Send(SCI_GETTABMINIMUMWIDTH, 0, 0);
}

void jaeTextEditControl::clearTabStops(sptr_t line) {
    Send(SCI_CLEARTABSTOPS, line, 0);
}

void jaeTextEditControl::addTabStop(sptr_t line, sptr_t x) {
    Send(SCI_ADDTABSTOP, line, x);
}

auto  jaeTextEditControl::getNextTabStop(sptr_t line, sptr_t x) -> sptr_t {
    return Send(SCI_GETNEXTTABSTOP, line, x);
}

void jaeTextEditControl::setCodePage(sptr_t codePage) {
    Send(SCI_SETCODEPAGE, codePage, 0);
}

void jaeTextEditControl::setFontLocale(const char * localeName) {
    Send(SCI_SETFONTLOCALE, 0, (sptr_t)localeName);
}

auto  jaeTextEditControl::fontLocale() const -> wxCharBuffer {
    return TextReturner(SCI_GETFONTLOCALE, 0);
}

auto  jaeTextEditControl::iMEInteraction() const -> sptr_t {
    return Send(SCI_GETIMEINTERACTION, 0, 0);
}

void jaeTextEditControl::setIMEInteraction(sptr_t imeInteraction) {
    Send(SCI_SETIMEINTERACTION, imeInteraction, 0);
}

void jaeTextEditControl::markerDefine(sptr_t markerNumber, sptr_t markerSymbol) {
    Send(SCI_MARKERDEFINE, markerNumber, markerSymbol);
}

void jaeTextEditControl::markerSetFore(sptr_t markerNumber, sptr_t fore) {
    Send(SCI_MARKERSETFORE, markerNumber, fore);
}

void jaeTextEditControl::markerSetBack(sptr_t markerNumber, sptr_t back) {
    Send(SCI_MARKERSETBACK, markerNumber, back);
}

void jaeTextEditControl::markerSetBackSelected(sptr_t markerNumber, sptr_t back) {
    Send(SCI_MARKERSETBACKSELECTED, markerNumber, back);
}

void jaeTextEditControl::markerSetForeTranslucent(sptr_t markerNumber, sptr_t fore) {
    Send(SCI_MARKERSETFORETRANSLUCENT, markerNumber, fore);
}

void jaeTextEditControl::markerSetBackTranslucent(sptr_t markerNumber, sptr_t back) {
    Send(SCI_MARKERSETBACKTRANSLUCENT, markerNumber, back);
}

void jaeTextEditControl::markerSetBackSelectedTranslucent(sptr_t markerNumber, sptr_t back) {
    Send(SCI_MARKERSETBACKSELECTEDTRANSLUCENT, markerNumber, back);
}

void jaeTextEditControl::markerSetStrokeWidth(sptr_t markerNumber, sptr_t hundredths) {
    Send(SCI_MARKERSETSTROKEWIDTH, markerNumber, hundredths);
}

void jaeTextEditControl::markerEnableHighlight(bool enabled) {
    Send(SCI_MARKERENABLEHIGHLIGHT, enabled, 0);
}

auto  jaeTextEditControl::markerAdd(sptr_t line, sptr_t markerNumber) -> sptr_t {
    return Send(SCI_MARKERADD, line, markerNumber);
}

void jaeTextEditControl::markerDelete(sptr_t line, sptr_t markerNumber) {
    Send(SCI_MARKERDELETE, line, markerNumber);
}

void jaeTextEditControl::markerDeleteAll(sptr_t markerNumber) {
    Send(SCI_MARKERDELETEALL, markerNumber, 0);
}

auto  jaeTextEditControl::markerGet(sptr_t line) -> sptr_t {
    return Send(SCI_MARKERGET, line, 0);
}

auto  jaeTextEditControl::markerNext(sptr_t lineStart, sptr_t markerMask) -> sptr_t {
    return Send(SCI_MARKERNEXT, lineStart, markerMask);
}

auto  jaeTextEditControl::markerPrevious(sptr_t lineStart, sptr_t markerMask) -> sptr_t {
    return Send(SCI_MARKERPREVIOUS, lineStart, markerMask);
}

void jaeTextEditControl::markerDefinePixmap(sptr_t markerNumber, const char * pixmap) {
    Send(SCI_MARKERDEFINEPIXMAP, markerNumber, (sptr_t)pixmap);
}

void jaeTextEditControl::markerAddSet(sptr_t line, sptr_t markerSet) {
    Send(SCI_MARKERADDSET, line, markerSet);
}

void jaeTextEditControl::markerSetAlpha(sptr_t markerNumber, sptr_t alpha) {
    Send(SCI_MARKERSETALPHA, markerNumber, alpha);
}

auto  jaeTextEditControl::markerLayer(sptr_t markerNumber) const -> sptr_t {
    return Send(SCI_MARKERGETLAYER, markerNumber, 0);
}

void jaeTextEditControl::markerSetLayer(sptr_t markerNumber, sptr_t layer) {
    Send(SCI_MARKERSETLAYER, markerNumber, layer);
}

void jaeTextEditControl::setMarginTypeN(sptr_t margin, sptr_t marginType) {
    Send(SCI_SETMARGINTYPEN, margin, marginType);
}

auto  jaeTextEditControl::marginTypeN(sptr_t margin) const -> sptr_t {
    return Send(SCI_GETMARGINTYPEN, margin, 0);
}

void jaeTextEditControl::setMarginWidthN(sptr_t margin, sptr_t pixelWidth) {
    Send(SCI_SETMARGINWIDTHN, margin, pixelWidth);
}

auto  jaeTextEditControl::marginWidthN(sptr_t margin) const -> sptr_t {
    return Send(SCI_GETMARGINWIDTHN, margin, 0);
}

void jaeTextEditControl::setMarginMaskN(sptr_t margin, sptr_t mask) {
    Send(SCI_SETMARGINMASKN, margin, mask);
}

auto  jaeTextEditControl::marginMaskN(sptr_t margin) const -> sptr_t {
    return Send(SCI_GETMARGINMASKN, margin, 0);
}

void jaeTextEditControl::setMarginSensitiveN(sptr_t margin, bool sensitive) {
    Send(SCI_SETMARGINSENSITIVEN, margin, sensitive);
}

auto  jaeTextEditControl::marginSensitiveN(sptr_t margin) const -> bool {
    return Send(SCI_GETMARGINSENSITIVEN, margin, 0);
}

void jaeTextEditControl::setMarginCursorN(sptr_t margin, sptr_t cursor) {
    Send(SCI_SETMARGINCURSORN, margin, cursor);
}

auto  jaeTextEditControl::marginCursorN(sptr_t margin) const -> sptr_t {
    return Send(SCI_GETMARGINCURSORN, margin, 0);
}

void jaeTextEditControl::setMarginBackN(sptr_t margin, sptr_t back) {
    Send(SCI_SETMARGINBACKN, margin, back);
}

auto  jaeTextEditControl::marginBackN(sptr_t margin) const -> sptr_t {
    return Send(SCI_GETMARGINBACKN, margin, 0);
}

void jaeTextEditControl::setMargins(sptr_t margins) {
    Send(SCI_SETMARGINS, margins, 0);
}

auto  jaeTextEditControl::margins() const -> sptr_t {
    return Send(SCI_GETMARGINS, 0, 0);
}

void jaeTextEditControl::styleClearAll() {
    Send(SCI_STYLECLEARALL, 0, 0);
}

void jaeTextEditControl::styleSetFore(sptr_t style, sptr_t fore) {
    Send(SCI_STYLESETFORE, style, fore);
}

void jaeTextEditControl::styleSetBack(sptr_t style, sptr_t back) {
    Send(SCI_STYLESETBACK, style, back);
}

void jaeTextEditControl::styleSetBold(sptr_t style, bool bold) {
    Send(SCI_STYLESETBOLD, style, bold);
}

void jaeTextEditControl::styleSetItalic(sptr_t style, bool italic) {
    Send(SCI_STYLESETITALIC, style, italic);
}

void jaeTextEditControl::styleSetSize(sptr_t style, sptr_t sizePoints) {
    Send(SCI_STYLESETSIZE, style, sizePoints);
}

void jaeTextEditControl::styleSetFont(sptr_t style, const char * fontName) {
    Send(SCI_STYLESETFONT, style, (sptr_t)fontName);
}

void jaeTextEditControl::styleSetEOLFilled(sptr_t style, bool eolFilled) {
    Send(SCI_STYLESETEOLFILLED, style, eolFilled);
}

void jaeTextEditControl::styleResetDefault() {
    Send(SCI_STYLERESETDEFAULT, 0, 0);
}

void jaeTextEditControl::styleSetUnderline(sptr_t style, bool underline) {
    Send(SCI_STYLESETUNDERLINE, style, underline);
}

auto  jaeTextEditControl::styleFore(sptr_t style) const -> sptr_t {
    return Send(SCI_STYLEGETFORE, style, 0);
}

auto  jaeTextEditControl::styleBack(sptr_t style) const -> sptr_t {
    return Send(SCI_STYLEGETBACK, style, 0);
}

auto  jaeTextEditControl::styleBold(sptr_t style) const -> bool {
    return Send(SCI_STYLEGETBOLD, style, 0);
}

auto  jaeTextEditControl::styleItalic(sptr_t style) const -> bool {
    return Send(SCI_STYLEGETITALIC, style, 0);
}

auto  jaeTextEditControl::styleSize(sptr_t style) const -> sptr_t {
    return Send(SCI_STYLEGETSIZE, style, 0);
}

auto  jaeTextEditControl::styleFont(sptr_t style) const -> wxCharBuffer {
    return TextReturner(SCI_STYLEGETFONT, style);
}

auto  jaeTextEditControl::styleEOLFilled(sptr_t style) const -> bool {
    return Send(SCI_STYLEGETEOLFILLED, style, 0);
}

auto  jaeTextEditControl::styleUnderline(sptr_t style) const -> bool {
    return Send(SCI_STYLEGETUNDERLINE, style, 0);
}

auto  jaeTextEditControl::styleCase(sptr_t style) const -> sptr_t {
    return Send(SCI_STYLEGETCASE, style, 0);
}

auto  jaeTextEditControl::styleCharacterSet(sptr_t style) const -> sptr_t {
    return Send(SCI_STYLEGETCHARACTERSET, style, 0);
}

auto  jaeTextEditControl::styleVisible(sptr_t style) const -> bool {
    return Send(SCI_STYLEGETVISIBLE, style, 0);
}

auto  jaeTextEditControl::styleChangeable(sptr_t style) const -> bool {
    return Send(SCI_STYLEGETCHANGEABLE, style, 0);
}

auto  jaeTextEditControl::styleHotSpot(sptr_t style) const -> bool {
    return Send(SCI_STYLEGETHOTSPOT, style, 0);
}

void jaeTextEditControl::styleSetCase(sptr_t style, sptr_t caseVisible) {
    Send(SCI_STYLESETCASE, style, caseVisible);
}

void jaeTextEditControl::styleSetSizeFractional(sptr_t style, sptr_t sizeHundredthPoints) {
    Send(SCI_STYLESETSIZEFRACTIONAL, style, sizeHundredthPoints);
}

auto  jaeTextEditControl::styleSizeFractional(sptr_t style) const -> sptr_t {
    return Send(SCI_STYLEGETSIZEFRACTIONAL, style, 0);
}

void jaeTextEditControl::styleSetWeight(sptr_t style, sptr_t weight) {
    Send(SCI_STYLESETWEIGHT, style, weight);
}

auto  jaeTextEditControl::styleWeight(sptr_t style) const -> sptr_t {
    return Send(SCI_STYLEGETWEIGHT, style, 0);
}

void jaeTextEditControl::styleSetCharacterSet(sptr_t style, sptr_t characterSet) {
    Send(SCI_STYLESETCHARACTERSET, style, characterSet);
}

void jaeTextEditControl::styleSetHotSpot(sptr_t style, bool hotspot) {
    Send(SCI_STYLESETHOTSPOT, style, hotspot);
}

void jaeTextEditControl::setElementColour(sptr_t element, sptr_t colourElement) {
    Send(SCI_SETELEMENTCOLOUR, element, colourElement);
}

auto  jaeTextEditControl::elementColour(sptr_t element) const -> sptr_t {
    return Send(SCI_GETELEMENTCOLOUR, element, 0);
}

void jaeTextEditControl::resetElementColour(sptr_t element) {
    Send(SCI_RESETELEMENTCOLOUR, element, 0);
}

auto  jaeTextEditControl::elementIsSet(sptr_t element) const -> bool {
    return Send(SCI_GETELEMENTISSET, element, 0);
}

auto  jaeTextEditControl::elementAllowsTranslucent(sptr_t element) const -> bool {
    return Send(SCI_GETELEMENTALLOWSTRANSLUCENT, element, 0);
}

auto  jaeTextEditControl::elementBaseColour(sptr_t element) const -> sptr_t {
    return Send(SCI_GETELEMENTBASECOLOUR, element, 0);
}

void jaeTextEditControl::setSelFore(bool useSetting, sptr_t fore) {
    Send(SCI_SETSELFORE, useSetting, fore);
}

void jaeTextEditControl::setSelBack(bool useSetting, sptr_t back) {
    Send(SCI_SETSELBACK, useSetting, back);
}

auto  jaeTextEditControl::selAlpha() const -> sptr_t {
    return Send(SCI_GETSELALPHA, 0, 0);
}

void jaeTextEditControl::setSelAlpha(sptr_t alpha) {
    Send(SCI_SETSELALPHA, alpha, 0);
}

auto  jaeTextEditControl::selEOLFilled() const -> bool {
    return Send(SCI_GETSELEOLFILLED, 0, 0);
}

void jaeTextEditControl::setSelEOLFilled(bool filled) {
    Send(SCI_SETSELEOLFILLED, filled, 0);
}

auto  jaeTextEditControl::selectionLayer() const -> sptr_t {
    return Send(SCI_GETSELECTIONLAYER, 0, 0);
}

void jaeTextEditControl::setSelectionLayer(sptr_t layer) {
    Send(SCI_SETSELECTIONLAYER, layer, 0);
}

auto  jaeTextEditControl::caretLineLayer() const -> sptr_t {
    return Send(SCI_GETCARETLINELAYER, 0, 0);
}

void jaeTextEditControl::setCaretLineLayer(sptr_t layer) {
    Send(SCI_SETCARETLINELAYER, layer, 0);
}

void jaeTextEditControl::setCaretFore(sptr_t fore) {
    Send(SCI_SETCARETFORE, fore, 0);
}

void jaeTextEditControl::assignCmdKey(sptr_t keyDefinition, sptr_t sciCommand) {
    Send(SCI_ASSIGNCMDKEY, keyDefinition, sciCommand);
}

void jaeTextEditControl::clearCmdKey(sptr_t keyDefinition) {
    Send(SCI_CLEARCMDKEY, keyDefinition, 0);
}

void jaeTextEditControl::clearAllCmdKeys() {
    Send(SCI_CLEARALLCMDKEYS, 0, 0);
}

void jaeTextEditControl::setStylingEx(sptr_t length, const char * styles) {
    Send(SCI_SETSTYLINGEX, length, (sptr_t)styles);
}

void jaeTextEditControl::styleSetVisible(sptr_t style, bool visible) {
    Send(SCI_STYLESETVISIBLE, style, visible);
}

auto  jaeTextEditControl::caretPeriod() const -> sptr_t {
    return Send(SCI_GETCARETPERIOD, 0, 0);
}

void jaeTextEditControl::setCaretPeriod(sptr_t periodMilliseconds) {
    Send(SCI_SETCARETPERIOD, periodMilliseconds, 0);
}

void jaeTextEditControl::setWordChars(const char * characters) {
    Send(SCI_SETWORDCHARS, 0, (sptr_t)characters);
}

auto  jaeTextEditControl::wordChars() const -> wxCharBuffer {
    return TextReturner(SCI_GETWORDCHARS, 0);
}

void jaeTextEditControl::setCharacterCategoryOptimization(sptr_t countCharacters) {
    Send(SCI_SETCHARACTERCATEGORYOPTIMIZATION, countCharacters, 0);
}

auto  jaeTextEditControl::characterCategoryOptimization() const -> sptr_t {
    return Send(SCI_GETCHARACTERCATEGORYOPTIMIZATION, 0, 0);
}

void jaeTextEditControl::beginUndoAction() {
    Send(SCI_BEGINUNDOACTION, 0, 0);
}

void jaeTextEditControl::endUndoAction() {
    Send(SCI_ENDUNDOACTION, 0, 0);
}

void jaeTextEditControl::indicSetStyle(sptr_t indicator, sptr_t indicatorStyle) {
    Send(SCI_INDICSETSTYLE, indicator, indicatorStyle);
}

auto  jaeTextEditControl::indicStyle(sptr_t indicator) const -> sptr_t {
    return Send(SCI_INDICGETSTYLE, indicator, 0);
}

void jaeTextEditControl::indicSetFore(sptr_t indicator, sptr_t fore) {
    Send(SCI_INDICSETFORE, indicator, fore);
}

auto  jaeTextEditControl::indicFore(sptr_t indicator) const -> sptr_t {
    return Send(SCI_INDICGETFORE, indicator, 0);
}

void jaeTextEditControl::indicSetUnder(sptr_t indicator, bool under) {
    Send(SCI_INDICSETUNDER, indicator, under);
}

auto  jaeTextEditControl::indicUnder(sptr_t indicator) const -> bool {
    return Send(SCI_INDICGETUNDER, indicator, 0);
}

void jaeTextEditControl::indicSetHoverStyle(sptr_t indicator, sptr_t indicatorStyle) {
    Send(SCI_INDICSETHOVERSTYLE, indicator, indicatorStyle);
}

auto  jaeTextEditControl::indicHoverStyle(sptr_t indicator) const -> sptr_t {
    return Send(SCI_INDICGETHOVERSTYLE, indicator, 0);
}

void jaeTextEditControl::indicSetHoverFore(sptr_t indicator, sptr_t fore) {
    Send(SCI_INDICSETHOVERFORE, indicator, fore);
}

auto  jaeTextEditControl::indicHoverFore(sptr_t indicator) const -> sptr_t {
    return Send(SCI_INDICGETHOVERFORE, indicator, 0);
}

void jaeTextEditControl::indicSetFlags(sptr_t indicator, sptr_t flags) {
    Send(SCI_INDICSETFLAGS, indicator, flags);
}

auto  jaeTextEditControl::indicFlags(sptr_t indicator) const -> sptr_t {
    return Send(SCI_INDICGETFLAGS, indicator, 0);
}

void jaeTextEditControl::indicSetStrokeWidth(sptr_t indicator, sptr_t hundredths) {
    Send(SCI_INDICSETSTROKEWIDTH, indicator, hundredths);
}

auto  jaeTextEditControl::indicStrokeWidth(sptr_t indicator) const -> sptr_t {
    return Send(SCI_INDICGETSTROKEWIDTH, indicator, 0);
}

void jaeTextEditControl::setWhitespaceFore(bool useSetting, sptr_t fore) {
    Send(SCI_SETWHITESPACEFORE, useSetting, fore);
}

void jaeTextEditControl::setWhitespaceBack(bool useSetting, sptr_t back) {
    Send(SCI_SETWHITESPACEBACK, useSetting, back);
}

void jaeTextEditControl::setWhitespaceSize(sptr_t size) {
    Send(SCI_SETWHITESPACESIZE, size, 0);
}

auto  jaeTextEditControl::whitespaceSize() const -> sptr_t {
    return Send(SCI_GETWHITESPACESIZE, 0, 0);
}

void jaeTextEditControl::setLineState(sptr_t line, sptr_t state) {
    Send(SCI_SETLINESTATE, line, state);
}

auto  jaeTextEditControl::lineState(sptr_t line) const -> sptr_t {
    return Send(SCI_GETLINESTATE, line, 0);
}

auto  jaeTextEditControl::maxLineState() const -> sptr_t {
    return Send(SCI_GETMAXLINESTATE, 0, 0);
}

auto  jaeTextEditControl::caretLineVisible() const -> bool {
    return Send(SCI_GETCARETLINEVISIBLE, 0, 0);
}

void jaeTextEditControl::setCaretLineVisible(bool show) {
    Send(SCI_SETCARETLINEVISIBLE, show, 0);
}

auto  jaeTextEditControl::caretLineBack() const -> sptr_t {
    return Send(SCI_GETCARETLINEBACK, 0, 0);
}

void jaeTextEditControl::setCaretLineBack(sptr_t back) {
    Send(SCI_SETCARETLINEBACK, back, 0);
}

auto  jaeTextEditControl::caretLineFrame() const -> sptr_t {
    return Send(SCI_GETCARETLINEFRAME, 0, 0);
}

void jaeTextEditControl::setCaretLineFrame(sptr_t width) {
    Send(SCI_SETCARETLINEFRAME, width, 0);
}

void jaeTextEditControl::styleSetChangeable(sptr_t style, bool changeable) {
    Send(SCI_STYLESETCHANGEABLE, style, changeable);
}

void jaeTextEditControl::autoCShow(sptr_t lengthEntered, const char * itemList) {
    Send(SCI_AUTOCSHOW, lengthEntered, (sptr_t)itemList);
}

void jaeTextEditControl::autoCCancel() {
    Send(SCI_AUTOCCANCEL, 0, 0);
}

auto  jaeTextEditControl::autoCActive() -> bool {
    return Send(SCI_AUTOCACTIVE, 0, 0);
}

auto  jaeTextEditControl::autoCPosStart() -> sptr_t {
    return Send(SCI_AUTOCPOSSTART, 0, 0);
}

void jaeTextEditControl::autoCComplete() {
    Send(SCI_AUTOCCOMPLETE, 0, 0);
}

void jaeTextEditControl::autoCStops(const char * characterSet) {
    Send(SCI_AUTOCSTOPS, 0, (sptr_t)characterSet);
}

void jaeTextEditControl::autoCSetSeparator(sptr_t separatorCharacter) {
    Send(SCI_AUTOCSETSEPARATOR, separatorCharacter, 0);
}

auto  jaeTextEditControl::autoCSeparator() const -> sptr_t {
    return Send(SCI_AUTOCGETSEPARATOR, 0, 0);
}

void jaeTextEditControl::autoCSelect(const char * select) {
    Send(SCI_AUTOCSELECT, 0, (sptr_t)select);
}

void jaeTextEditControl::autoCSetCancelAtStart(bool cancel) {
    Send(SCI_AUTOCSETCANCELATSTART, cancel, 0);
}

auto  jaeTextEditControl::autoCCancelAtStart() const -> bool {
    return Send(SCI_AUTOCGETCANCELATSTART, 0, 0);
}

void jaeTextEditControl::autoCSetFillUps(const char * characterSet) {
    Send(SCI_AUTOCSETFILLUPS, 0, (sptr_t)characterSet);
}

void jaeTextEditControl::autoCSetChooseSingle(bool chooseSingle) {
    Send(SCI_AUTOCSETCHOOSESINGLE, chooseSingle, 0);
}

auto  jaeTextEditControl::autoCChooseSingle() const -> bool {
    return Send(SCI_AUTOCGETCHOOSESINGLE, 0, 0);
}

void jaeTextEditControl::autoCSetIgnoreCase(bool ignoreCase) {
    Send(SCI_AUTOCSETIGNORECASE, ignoreCase, 0);
}

auto  jaeTextEditControl::autoCIgnoreCase() const -> bool {
    return Send(SCI_AUTOCGETIGNORECASE, 0, 0);
}

void jaeTextEditControl::userListShow(sptr_t listType, const char * itemList) {
    Send(SCI_USERLISTSHOW, listType, (sptr_t)itemList);
}

void jaeTextEditControl::autoCSetAutoHide(bool autoHide) {
    Send(SCI_AUTOCSETAUTOHIDE, autoHide, 0);
}

auto  jaeTextEditControl::autoCAutoHide() const -> bool {
    return Send(SCI_AUTOCGETAUTOHIDE, 0, 0);
}

void jaeTextEditControl::autoCSetOptions(sptr_t options) {
    Send(SCI_AUTOCSETOPTIONS, options, 0);
}

auto  jaeTextEditControl::autoCOptions() const -> sptr_t {
    return Send(SCI_AUTOCGETOPTIONS, 0, 0);
}

void jaeTextEditControl::autoCSetDropRestOfWord(bool dropRestOfWord) {
    Send(SCI_AUTOCSETDROPRESTOFWORD, dropRestOfWord, 0);
}

auto  jaeTextEditControl::autoCDropRestOfWord() const -> bool {
    return Send(SCI_AUTOCGETDROPRESTOFWORD, 0, 0);
}

void jaeTextEditControl::registerImage(sptr_t type, const char * xpmData) {
    Send(SCI_REGISTERIMAGE, type, (sptr_t)xpmData);
}

void jaeTextEditControl::clearRegisteredImages() {
    Send(SCI_CLEARREGISTEREDIMAGES, 0, 0);
}

auto  jaeTextEditControl::autoCTypeSeparator() const -> sptr_t {
    return Send(SCI_AUTOCGETTYPESEPARATOR, 0, 0);
}

void jaeTextEditControl::autoCSetTypeSeparator(sptr_t separatorCharacter) {
    Send(SCI_AUTOCSETTYPESEPARATOR, separatorCharacter, 0);
}

void jaeTextEditControl::autoCSetMaxWidth(sptr_t characterCount) {
    Send(SCI_AUTOCSETMAXWIDTH, characterCount, 0);
}

auto  jaeTextEditControl::autoCMaxWidth() const -> sptr_t {
    return Send(SCI_AUTOCGETMAXWIDTH, 0, 0);
}

void jaeTextEditControl::autoCSetMaxHeight(sptr_t rowCount) {
    Send(SCI_AUTOCSETMAXHEIGHT, rowCount, 0);
}

auto  jaeTextEditControl::autoCMaxHeight() const -> sptr_t {
    return Send(SCI_AUTOCGETMAXHEIGHT, 0, 0);
}

void jaeTextEditControl::setIndent(sptr_t indentSize) {
    Send(SCI_SETINDENT, indentSize, 0);
}

auto  jaeTextEditControl::indent() const -> sptr_t {
    return Send(SCI_GETINDENT, 0, 0);
}

void jaeTextEditControl::setUseTabs(bool useTabs) {
    Send(SCI_SETUSETABS, useTabs, 0);
}

auto  jaeTextEditControl::useTabs() const -> bool {
    return Send(SCI_GETUSETABS, 0, 0);
}

void jaeTextEditControl::setLineIndentation(sptr_t line, sptr_t indentation) {
    Send(SCI_SETLINEINDENTATION, line, indentation);
}

auto  jaeTextEditControl::lineIndentation(sptr_t line) const -> sptr_t {
    return Send(SCI_GETLINEINDENTATION, line, 0);
}

auto  jaeTextEditControl::lineIndentPosition(sptr_t line) const -> sptr_t {
    return Send(SCI_GETLINEINDENTPOSITION, line, 0);
}

auto  jaeTextEditControl::column(sptr_t pos) const -> sptr_t {
    return Send(SCI_GETCOLUMN, pos, 0);
}

auto  jaeTextEditControl::countCharacters(sptr_t start, sptr_t end) -> sptr_t {
    return Send(SCI_COUNTCHARACTERS, start, end);
}

auto  jaeTextEditControl::countCodeUnits(sptr_t start, sptr_t end) -> sptr_t {
    return Send(SCI_COUNTCODEUNITS, start, end);
}

void jaeTextEditControl::setHScrollBar(bool visible) {
    Send(SCI_SETHSCROLLBAR, visible, 0);
}

auto  jaeTextEditControl::hScrollBar() const -> bool {
    return Send(SCI_GETHSCROLLBAR, 0, 0);
}

void jaeTextEditControl::setIndentationGuides(sptr_t indentView) {
    Send(SCI_SETINDENTATIONGUIDES, indentView, 0);
}

auto  jaeTextEditControl::indentationGuides() const -> sptr_t {
    return Send(SCI_GETINDENTATIONGUIDES, 0, 0);
}

void jaeTextEditControl::setHighlightGuide(sptr_t column) {
    Send(SCI_SETHIGHLIGHTGUIDE, column, 0);
}

auto  jaeTextEditControl::highlightGuide() const -> sptr_t {
    return Send(SCI_GETHIGHLIGHTGUIDE, 0, 0);
}

auto  jaeTextEditControl::lineEndPosition(sptr_t line) const -> sptr_t {
    return Send(SCI_GETLINEENDPOSITION, line, 0);
}

auto  jaeTextEditControl::codePage() const -> sptr_t {
    return Send(SCI_GETCODEPAGE, 0, 0);
}

auto  jaeTextEditControl::caretFore() const -> sptr_t {
    return Send(SCI_GETCARETFORE, 0, 0);
}

auto  jaeTextEditControl::readOnly() const -> bool {
    return Send(SCI_GETREADONLY, 0, 0);
}

void jaeTextEditControl::setCurrentPos(sptr_t caret) {
    Send(SCI_SETCURRENTPOS, caret, 0);
}

void jaeTextEditControl::setSelectionStart(sptr_t anchor) {
    Send(SCI_SETSELECTIONSTART, anchor, 0);
}

auto  jaeTextEditControl::selectionStart() const -> sptr_t {
    return Send(SCI_GETSELECTIONSTART, 0, 0);
}

void jaeTextEditControl::setSelectionEnd(sptr_t caret) {
    Send(SCI_SETSELECTIONEND, caret, 0);
}

auto  jaeTextEditControl::selectionEnd() const -> sptr_t {
    return Send(SCI_GETSELECTIONEND, 0, 0);
}

void jaeTextEditControl::setEmptySelection(sptr_t caret) {
    Send(SCI_SETEMPTYSELECTION, caret, 0);
}

void jaeTextEditControl::setPrintMagnification(sptr_t magnification) {
    Send(SCI_SETPRINTMAGNIFICATION, magnification, 0);
}

auto  jaeTextEditControl::printMagnification() const -> sptr_t {
    return Send(SCI_GETPRINTMAGNIFICATION, 0, 0);
}

void jaeTextEditControl::setPrintColourMode(sptr_t mode) {
    Send(SCI_SETPRINTCOLOURMODE, mode, 0);
}

auto  jaeTextEditControl::printColourMode() const -> sptr_t {
    return Send(SCI_GETPRINTCOLOURMODE, 0, 0);
}

auto  jaeTextEditControl::firstVisibleLine() const -> sptr_t {
    return Send(SCI_GETFIRSTVISIBLELINE, 0, 0);
}

auto  jaeTextEditControl::getLine(sptr_t line) -> wxCharBuffer {
    return TextReturner(SCI_GETLINE, line);
}

auto  jaeTextEditControl::lineCount() const -> sptr_t {
    return Send(SCI_GETLINECOUNT, 0, 0);
}

void jaeTextEditControl::allocateLines(sptr_t lines) {
    Send(SCI_ALLOCATELINES, lines, 0);
}

void jaeTextEditControl::setMarginLeft(sptr_t pixelWidth) {
    Send(SCI_SETMARGINLEFT, 0, pixelWidth);
}

auto  jaeTextEditControl::marginLeft() const -> sptr_t {
    return Send(SCI_GETMARGINLEFT, 0, 0);
}

void jaeTextEditControl::setMarginRight(sptr_t pixelWidth) {
    Send(SCI_SETMARGINRIGHT, 0, pixelWidth);
}

auto  jaeTextEditControl::marginRight() const -> sptr_t {
    return Send(SCI_GETMARGINRIGHT, 0, 0);
}

auto  jaeTextEditControl::modify() const -> bool {
    return Send(SCI_GETMODIFY, 0, 0);
}

void jaeTextEditControl::setSel(sptr_t anchor, sptr_t caret) {
    Send(SCI_SETSEL, anchor, caret);
}

auto  jaeTextEditControl::getSelText() -> wxCharBuffer {
    return TextReturner(SCI_GETSELTEXT, 0);
}

void jaeTextEditControl::hideSelection(bool hide) {
    Send(SCI_HIDESELECTION, hide, 0);
}

auto  jaeTextEditControl::pointXFromPosition(sptr_t pos) -> sptr_t {
    return Send(SCI_POINTXFROMPOSITION, 0, pos);
}

auto  jaeTextEditControl::pointYFromPosition(sptr_t pos) -> sptr_t {
    return Send(SCI_POINTYFROMPOSITION, 0, pos);
}

auto  jaeTextEditControl::lineFromPosition(sptr_t pos) -> sptr_t {
    return Send(SCI_LINEFROMPOSITION, pos, 0);
}

auto  jaeTextEditControl::positionFromLine(sptr_t line) -> sptr_t {
    return Send(SCI_POSITIONFROMLINE, line, 0);
}

void jaeTextEditControl::lineScroll(sptr_t columns, sptr_t lines) {
    Send(SCI_LINESCROLL, columns, lines);
}

void jaeTextEditControl::scrollCaret() {
    Send(SCI_SCROLLCARET, 0, 0);
}

void jaeTextEditControl::scrollRange(sptr_t secondary, sptr_t primary) {
    Send(SCI_SCROLLRANGE, secondary, primary);
}

void jaeTextEditControl::replaceSel(const char * text) {
    Send(SCI_REPLACESEL, 0, (sptr_t)text);
}

void jaeTextEditControl::setReadOnly(bool readOnly) {
    Send(SCI_SETREADONLY, readOnly, 0);
}

void jaeTextEditControl::null() {
    Send(SCI_NULL, 0, 0);
}

auto  jaeTextEditControl::canPaste() -> bool {
    return Send(SCI_CANPASTE, 0, 0);
}

auto  jaeTextEditControl::canUndo() -> bool {
    return Send(SCI_CANUNDO, 0, 0);
}

void jaeTextEditControl::emptyUndoBuffer() {
    Send(SCI_EMPTYUNDOBUFFER, 0, 0);
}

void jaeTextEditControl::undo() {
    Send(SCI_UNDO, 0, 0);
}

void jaeTextEditControl::cut() {
    Send(SCI_CUT, 0, 0);
}

void jaeTextEditControl::copy() {
    Send(SCI_COPY, 0, 0);
}

void jaeTextEditControl::paste() {
    Send(SCI_PASTE, 0, 0);
}

void jaeTextEditControl::clear() {
    Send(SCI_CLEAR, 0, 0);
}

void jaeTextEditControl::setText(const char * text) {
    Send(SCI_SETTEXT, 0, (sptr_t)text);
}

auto  jaeTextEditControl::getText(sptr_t length) -> wxCharBuffer {
    return TextReturner(SCI_GETTEXT, length);
}

auto  jaeTextEditControl::textLength() const -> sptr_t {
    return Send(SCI_GETTEXTLENGTH, 0, 0);
}

auto  jaeTextEditControl::directFunction() const -> sptr_t {
    return Send(SCI_GETDIRECTFUNCTION, 0, 0);
}

auto  jaeTextEditControl::directStatusFunction() const -> sptr_t {
    return Send(SCI_GETDIRECTSTATUSFUNCTION, 0, 0);
}

auto  jaeTextEditControl::directPointer() const -> sptr_t {
    return Send(SCI_GETDIRECTPOINTER, 0, 0);
}

void jaeTextEditControl::setOvertype(bool overType) {
    Send(SCI_SETOVERTYPE, overType, 0);
}

auto  jaeTextEditControl::overtype() const -> bool {
    return Send(SCI_GETOVERTYPE, 0, 0);
}

void jaeTextEditControl::setCaretWidth(sptr_t pixelWidth) {
    Send(SCI_SETCARETWIDTH, pixelWidth, 0);
}

auto  jaeTextEditControl::caretWidth() const -> sptr_t {
    return Send(SCI_GETCARETWIDTH, 0, 0);
}

void jaeTextEditControl::setTargetStart(sptr_t start) {
    Send(SCI_SETTARGETSTART, start, 0);
}

auto  jaeTextEditControl::targetStart() const -> sptr_t {
    return Send(SCI_GETTARGETSTART, 0, 0);
}

void jaeTextEditControl::setTargetStartVirtualSpace(sptr_t space) {
    Send(SCI_SETTARGETSTARTVIRTUALSPACE, space, 0);
}

auto  jaeTextEditControl::targetStartVirtualSpace() const -> sptr_t {
    return Send(SCI_GETTARGETSTARTVIRTUALSPACE, 0, 0);
}

void jaeTextEditControl::setTargetEnd(sptr_t end) {
    Send(SCI_SETTARGETEND, end, 0);
}

auto  jaeTextEditControl::targetEnd() const -> sptr_t {
    return Send(SCI_GETTARGETEND, 0, 0);
}

void jaeTextEditControl::setTargetEndVirtualSpace(sptr_t space) {
    Send(SCI_SETTARGETENDVIRTUALSPACE, space, 0);
}

auto  jaeTextEditControl::targetEndVirtualSpace() const -> sptr_t {
    return Send(SCI_GETTARGETENDVIRTUALSPACE, 0, 0);
}

void jaeTextEditControl::setTargetRange(sptr_t start, sptr_t end) {
    Send(SCI_SETTARGETRANGE, start, end);
}

auto  jaeTextEditControl::targetText() const -> wxCharBuffer {
    return TextReturner(SCI_GETTARGETTEXT, 0);
}

void jaeTextEditControl::targetFromSelection() {
    Send(SCI_TARGETFROMSELECTION, 0, 0);
}

void jaeTextEditControl::targetWholeDocument() {
    Send(SCI_TARGETWHOLEDOCUMENT, 0, 0);
}

auto  jaeTextEditControl::replaceTarget(sptr_t length, const char * text) -> sptr_t {
    return Send(SCI_REPLACETARGET, length, (sptr_t)text);
}

auto  jaeTextEditControl::replaceTargetRE(sptr_t length, const char * text) -> sptr_t {
    return Send(SCI_REPLACETARGETRE, length, (sptr_t)text);
}

auto  jaeTextEditControl::searchInTarget(sptr_t length, const char * text) -> sptr_t {
    return Send(SCI_SEARCHINTARGET, length, (sptr_t)text);
}

void jaeTextEditControl::setSearchFlags(sptr_t searchFlags) {
    Send(SCI_SETSEARCHFLAGS, searchFlags, 0);
}

auto  jaeTextEditControl::searchFlags() const -> sptr_t {
    return Send(SCI_GETSEARCHFLAGS, 0, 0);
}

void jaeTextEditControl::callTipShow(sptr_t pos, const char * definition) {
    Send(SCI_CALLTIPSHOW, pos, (sptr_t)definition);
}

void jaeTextEditControl::callTipCancel() {
    Send(SCI_CALLTIPCANCEL, 0, 0);
}

auto  jaeTextEditControl::callTipActive() -> bool {
    return Send(SCI_CALLTIPACTIVE, 0, 0);
}

auto  jaeTextEditControl::callTipPosStart() -> sptr_t {
    return Send(SCI_CALLTIPPOSSTART, 0, 0);
}

void jaeTextEditControl::callTipSetPosStart(sptr_t posStart) {
    Send(SCI_CALLTIPSETPOSSTART, posStart, 0);
}

void jaeTextEditControl::callTipSetHlt(sptr_t highlightStart, sptr_t highlightEnd) {
    Send(SCI_CALLTIPSETHLT, highlightStart, highlightEnd);
}

void jaeTextEditControl::callTipSetBack(sptr_t back) {
    Send(SCI_CALLTIPSETBACK, back, 0);
}

void jaeTextEditControl::callTipSetFore(sptr_t fore) {
    Send(SCI_CALLTIPSETFORE, fore, 0);
}

void jaeTextEditControl::callTipSetForeHlt(sptr_t fore) {
    Send(SCI_CALLTIPSETFOREHLT, fore, 0);
}

void jaeTextEditControl::callTipUseStyle(sptr_t tabSize) {
    Send(SCI_CALLTIPUSESTYLE, tabSize, 0);
}

void jaeTextEditControl::callTipSetPosition(bool above) {
    Send(SCI_CALLTIPSETPOSITION, above, 0);
}

auto  jaeTextEditControl::visibleFromDocLine(sptr_t docLine) -> sptr_t {
    return Send(SCI_VISIBLEFROMDOCLINE, docLine, 0);
}

auto  jaeTextEditControl::docLineFromVisible(sptr_t displayLine) -> sptr_t {
    return Send(SCI_DOCLINEFROMVISIBLE, displayLine, 0);
}

auto  jaeTextEditControl::wrapCount(sptr_t docLine) -> sptr_t {
    return Send(SCI_WRAPCOUNT, docLine, 0);
}

void jaeTextEditControl::setFoldLevel(sptr_t line, sptr_t level) {
    Send(SCI_SETFOLDLEVEL, line, level);
}

auto  jaeTextEditControl::foldLevel(sptr_t line) const -> sptr_t {
    return Send(SCI_GETFOLDLEVEL, line, 0);
}

auto  jaeTextEditControl::lastChild(sptr_t line, sptr_t level) const -> sptr_t {
    return Send(SCI_GETLASTCHILD, line, level);
}

auto  jaeTextEditControl::foldParent(sptr_t line) const -> sptr_t {
    return Send(SCI_GETFOLDPARENT, line, 0);
}

void jaeTextEditControl::showLines(sptr_t lineStart, sptr_t lineEnd) {
    Send(SCI_SHOWLINES, lineStart, lineEnd);
}

void jaeTextEditControl::hideLines(sptr_t lineStart, sptr_t lineEnd) {
    Send(SCI_HIDELINES, lineStart, lineEnd);
}

auto  jaeTextEditControl::lineVisible(sptr_t line) const -> bool {
    return Send(SCI_GETLINEVISIBLE, line, 0);
}

auto  jaeTextEditControl::allLinesVisible() const -> bool {
    return Send(SCI_GETALLLINESVISIBLE, 0, 0);
}

void jaeTextEditControl::setFoldExpanded(sptr_t line, bool expanded) {
    Send(SCI_SETFOLDEXPANDED, line, expanded);
}

auto  jaeTextEditControl::foldExpanded(sptr_t line) const -> bool {
    return Send(SCI_GETFOLDEXPANDED, line, 0);
}

void jaeTextEditControl::toggleFold(sptr_t line) {
    Send(SCI_TOGGLEFOLD, line, 0);
}

void jaeTextEditControl::toggleFoldShowText(sptr_t line, const char * text) {
    Send(SCI_TOGGLEFOLDSHOWTEXT, line, (sptr_t)text);
}

void jaeTextEditControl::foldDisplayTextSetStyle(sptr_t style) {
    Send(SCI_FOLDDISPLAYTEXTSETSTYLE, style, 0);
}

auto  jaeTextEditControl::foldDisplayTextStyle() const -> sptr_t {
    return Send(SCI_FOLDDISPLAYTEXTGETSTYLE, 0, 0);
}

void jaeTextEditControl::setDefaultFoldDisplayText(const char * text) {
    Send(SCI_SETDEFAULTFOLDDISPLAYTEXT, 0, (sptr_t)text);
}

auto  jaeTextEditControl::getDefaultFoldDisplayText() -> wxCharBuffer {
    return TextReturner(SCI_GETDEFAULTFOLDDISPLAYTEXT, 0);
}

void jaeTextEditControl::foldLine(sptr_t line, sptr_t action) {
    Send(SCI_FOLDLINE, line, action);
}

void jaeTextEditControl::foldChildren(sptr_t line, sptr_t action) {
    Send(SCI_FOLDCHILDREN, line, action);
}

void jaeTextEditControl::expandChildren(sptr_t line, sptr_t level) {
    Send(SCI_EXPANDCHILDREN, line, level);
}

void jaeTextEditControl::foldAll(sptr_t action) {
    Send(SCI_FOLDALL, action, 0);
}

void jaeTextEditControl::ensureVisible(sptr_t line) {
    Send(SCI_ENSUREVISIBLE, line, 0);
}

void jaeTextEditControl::setAutomaticFold(sptr_t automaticFold) {
    Send(SCI_SETAUTOMATICFOLD, automaticFold, 0);
}

auto  jaeTextEditControl::automaticFold() const -> sptr_t {
    return Send(SCI_GETAUTOMATICFOLD, 0, 0);
}

void jaeTextEditControl::setFoldFlags(sptr_t flags) {
    Send(SCI_SETFOLDFLAGS, flags, 0);
}

void jaeTextEditControl::ensureVisibleEnforcePolicy(sptr_t line) {
    Send(SCI_ENSUREVISIBLEENFORCEPOLICY, line, 0);
}

void jaeTextEditControl::setTabIndents(bool tabIndents) {
    Send(SCI_SETTABINDENTS, tabIndents, 0);
}

auto  jaeTextEditControl::tabIndents() const -> bool {
    return Send(SCI_GETTABINDENTS, 0, 0);
}

void jaeTextEditControl::setBackSpaceUnIndents(bool bsUnIndents) {
    Send(SCI_SETBACKSPACEUNINDENTS, bsUnIndents, 0);
}

auto  jaeTextEditControl::backSpaceUnIndents() const -> bool {
    return Send(SCI_GETBACKSPACEUNINDENTS, 0, 0);
}

void jaeTextEditControl::setMouseDwellTime(sptr_t periodMilliseconds) {
    Send(SCI_SETMOUSEDWELLTIME, periodMilliseconds, 0);
}

auto  jaeTextEditControl::mouseDwellTime() const -> sptr_t {
    return Send(SCI_GETMOUSEDWELLTIME, 0, 0);
}

auto  jaeTextEditControl::wordStartPosition(sptr_t pos, bool onlyWordCharacters) -> sptr_t {
    return Send(SCI_WORDSTARTPOSITION, pos, onlyWordCharacters);
}

auto  jaeTextEditControl::wordEndPosition(sptr_t pos, bool onlyWordCharacters) -> sptr_t {
    return Send(SCI_WORDENDPOSITION, pos, onlyWordCharacters);
}

auto  jaeTextEditControl::isRangeWord(sptr_t start, sptr_t end) -> bool {
    return Send(SCI_ISRANGEWORD, start, end);
}

void jaeTextEditControl::setIdleStyling(sptr_t idleStyling) {
    Send(SCI_SETIDLESTYLING, idleStyling, 0);
}

auto  jaeTextEditControl::idleStyling() const -> sptr_t {
    return Send(SCI_GETIDLESTYLING, 0, 0);
}

void jaeTextEditControl::setWrapMode(sptr_t wrapMode) {
    Send(SCI_SETWRAPMODE, wrapMode, 0);
}

auto  jaeTextEditControl::wrapMode() const -> sptr_t {
    return Send(SCI_GETWRAPMODE, 0, 0);
}

void jaeTextEditControl::setWrapVisualFlags(sptr_t wrapVisualFlags) {
    Send(SCI_SETWRAPVISUALFLAGS, wrapVisualFlags, 0);
}

auto  jaeTextEditControl::wrapVisualFlags() const -> sptr_t {
    return Send(SCI_GETWRAPVISUALFLAGS, 0, 0);
}

void jaeTextEditControl::setWrapVisualFlagsLocation(sptr_t wrapVisualFlagsLocation) {
    Send(SCI_SETWRAPVISUALFLAGSLOCATION, wrapVisualFlagsLocation, 0);
}

auto  jaeTextEditControl::wrapVisualFlagsLocation() const -> sptr_t {
    return Send(SCI_GETWRAPVISUALFLAGSLOCATION, 0, 0);
}

void jaeTextEditControl::setWrapStartIndent(sptr_t indent) {
    Send(SCI_SETWRAPSTARTINDENT, indent, 0);
}

auto  jaeTextEditControl::wrapStartIndent() const -> sptr_t {
    return Send(SCI_GETWRAPSTARTINDENT, 0, 0);
}

void jaeTextEditControl::setWrapIndentMode(sptr_t wrapIndentMode) {
    Send(SCI_SETWRAPINDENTMODE, wrapIndentMode, 0);
}

auto  jaeTextEditControl::wrapIndentMode() const -> sptr_t {
    return Send(SCI_GETWRAPINDENTMODE, 0, 0);
}

void jaeTextEditControl::setLayoutCache(sptr_t cacheMode) {
    Send(SCI_SETLAYOUTCACHE, cacheMode, 0);
}

auto  jaeTextEditControl::layoutCache() const -> sptr_t {
    return Send(SCI_GETLAYOUTCACHE, 0, 0);
}

void jaeTextEditControl::setScrollWidth(sptr_t pixelWidth) {
    Send(SCI_SETSCROLLWIDTH, pixelWidth, 0);
}

auto  jaeTextEditControl::scrollWidth() const -> sptr_t {
    return Send(SCI_GETSCROLLWIDTH, 0, 0);
}

void jaeTextEditControl::setScrollWidthTracking(bool tracking) {
    Send(SCI_SETSCROLLWIDTHTRACKING, tracking, 0);
}

auto  jaeTextEditControl::scrollWidthTracking() const -> bool {
    return Send(SCI_GETSCROLLWIDTHTRACKING, 0, 0);
}

auto  jaeTextEditControl::textWidth(sptr_t style, const char * text) -> sptr_t {
    return Send(SCI_TEXTWIDTH, style, (sptr_t)text);
}

void jaeTextEditControl::setEndAtLastLine(bool endAtLastLine) {
    Send(SCI_SETENDATLASTLINE, endAtLastLine, 0);
}

auto  jaeTextEditControl::endAtLastLine() const -> bool {
    return Send(SCI_GETENDATLASTLINE, 0, 0);
}

auto  jaeTextEditControl::textHeight(sptr_t line) -> sptr_t {
    return Send(SCI_TEXTHEIGHT, line, 0);
}

void jaeTextEditControl::setVScrollBar(bool visible) {
    Send(SCI_SETVSCROLLBAR, visible, 0);
}

auto  jaeTextEditControl::vScrollBar() const -> bool {
    return Send(SCI_GETVSCROLLBAR, 0, 0);
}

void jaeTextEditControl::appendText(sptr_t length, const char * text) {
    Send(SCI_APPENDTEXT, length, (sptr_t)text);
}

auto  jaeTextEditControl::phasesDraw() const -> sptr_t {
    return Send(SCI_GETPHASESDRAW, 0, 0);
}

void jaeTextEditControl::setPhasesDraw(sptr_t phases) {
    Send(SCI_SETPHASESDRAW, phases, 0);
}

void jaeTextEditControl::setFontQuality(sptr_t fontQuality) {
    Send(SCI_SETFONTQUALITY, fontQuality, 0);
}

auto  jaeTextEditControl::fontQuality() const -> sptr_t {
    return Send(SCI_GETFONTQUALITY, 0, 0);
}

void jaeTextEditControl::setFirstVisibleLine(sptr_t displayLine) {
    Send(SCI_SETFIRSTVISIBLELINE, displayLine, 0);
}

void jaeTextEditControl::setMultiPaste(sptr_t multiPaste) {
    Send(SCI_SETMULTIPASTE, multiPaste, 0);
}

auto  jaeTextEditControl::multiPaste() const -> sptr_t {
    return Send(SCI_GETMULTIPASTE, 0, 0);
}

auto  jaeTextEditControl::tag(sptr_t tagNumber) const -> wxCharBuffer {
    return TextReturner(SCI_GETTAG, tagNumber);
}

void jaeTextEditControl::linesJoin() {
    Send(SCI_LINESJOIN, 0, 0);
}

void jaeTextEditControl::linesSplit(sptr_t pixelWidth) {
    Send(SCI_LINESSPLIT, pixelWidth, 0);
}

void jaeTextEditControl::setFoldMarginColour(bool useSetting, sptr_t back) {
    Send(SCI_SETFOLDMARGINCOLOUR, useSetting, back);
}

void jaeTextEditControl::setFoldMarginHiColour(bool useSetting, sptr_t fore) {
    Send(SCI_SETFOLDMARGINHICOLOUR, useSetting, fore);
}

void jaeTextEditControl::setAccessibility(sptr_t accessibility) {
    Send(SCI_SETACCESSIBILITY, accessibility, 0);
}

auto  jaeTextEditControl::accessibility() const -> sptr_t {
    return Send(SCI_GETACCESSIBILITY, 0, 0);
}

void jaeTextEditControl::lineDown() {
    Send(SCI_LINEDOWN, 0, 0);
}

void jaeTextEditControl::lineDownExtend() {
    Send(SCI_LINEDOWNEXTEND, 0, 0);
}

void jaeTextEditControl::lineUp() {
    Send(SCI_LINEUP, 0, 0);
}

void jaeTextEditControl::lineUpExtend() {
    Send(SCI_LINEUPEXTEND, 0, 0);
}

void jaeTextEditControl::charLeft() {
    Send(SCI_CHARLEFT, 0, 0);
}

void jaeTextEditControl::charLeftExtend() {
    Send(SCI_CHARLEFTEXTEND, 0, 0);
}

void jaeTextEditControl::charRight() {
    Send(SCI_CHARRIGHT, 0, 0);
}

void jaeTextEditControl::charRightExtend() {
    Send(SCI_CHARRIGHTEXTEND, 0, 0);
}

void jaeTextEditControl::wordLeft() {
    Send(SCI_WORDLEFT, 0, 0);
}

void jaeTextEditControl::wordLeftExtend() {
    Send(SCI_WORDLEFTEXTEND, 0, 0);
}

void jaeTextEditControl::wordRight() {
    Send(SCI_WORDRIGHT, 0, 0);
}

void jaeTextEditControl::wordRightExtend() {
    Send(SCI_WORDRIGHTEXTEND, 0, 0);
}

void jaeTextEditControl::home() {
    Send(SCI_HOME, 0, 0);
}

void jaeTextEditControl::homeExtend() {
    Send(SCI_HOMEEXTEND, 0, 0);
}

void jaeTextEditControl::lineEnd() {
    Send(SCI_LINEEND, 0, 0);
}

void jaeTextEditControl::lineEndExtend() {
    Send(SCI_LINEENDEXTEND, 0, 0);
}

void jaeTextEditControl::documentStart() {
    Send(SCI_DOCUMENTSTART, 0, 0);
}

void jaeTextEditControl::documentStartExtend() {
    Send(SCI_DOCUMENTSTARTEXTEND, 0, 0);
}

void jaeTextEditControl::documentEnd() {
    Send(SCI_DOCUMENTEND, 0, 0);
}

void jaeTextEditControl::documentEndExtend() {
    Send(SCI_DOCUMENTENDEXTEND, 0, 0);
}

void jaeTextEditControl::pageUp() {
    Send(SCI_PAGEUP, 0, 0);
}

void jaeTextEditControl::pageUpExtend() {
    Send(SCI_PAGEUPEXTEND, 0, 0);
}

void jaeTextEditControl::pageDown() {
    Send(SCI_PAGEDOWN, 0, 0);
}

void jaeTextEditControl::pageDownExtend() {
    Send(SCI_PAGEDOWNEXTEND, 0, 0);
}

void jaeTextEditControl::editToggleOvertype() {
    Send(SCI_EDITTOGGLEOVERTYPE, 0, 0);
}

void jaeTextEditControl::cancel() {
    Send(SCI_CANCEL, 0, 0);
}

void jaeTextEditControl::deleteBack() {
    Send(SCI_DELETEBACK, 0, 0);
}

void jaeTextEditControl::tab() {
    Send(SCI_TAB, 0, 0);
}

void jaeTextEditControl::backTab() {
    Send(SCI_BACKTAB, 0, 0);
}

void jaeTextEditControl::newLine() {
    Send(SCI_NEWLINE, 0, 0);
}

void jaeTextEditControl::formFeed() {
    Send(SCI_FORMFEED, 0, 0);
}

void jaeTextEditControl::vCHome() {
    Send(SCI_VCHOME, 0, 0);
}

void jaeTextEditControl::vCHomeExtend() {
    Send(SCI_VCHOMEEXTEND, 0, 0);
}

void jaeTextEditControl::zoomIn() {
    Send(SCI_ZOOMIN, 0, 0);
}

void jaeTextEditControl::zoomOut() {
    Send(SCI_ZOOMOUT, 0, 0);
}

void jaeTextEditControl::delWordLeft() {
    Send(SCI_DELWORDLEFT, 0, 0);
}

void jaeTextEditControl::delWordRight() {
    Send(SCI_DELWORDRIGHT, 0, 0);
}

void jaeTextEditControl::delWordRightEnd() {
    Send(SCI_DELWORDRIGHTEND, 0, 0);
}

void jaeTextEditControl::lineCut() {
    Send(SCI_LINECUT, 0, 0);
}

void jaeTextEditControl::lineDelete() {
    Send(SCI_LINEDELETE, 0, 0);
}

void jaeTextEditControl::lineTranspose() {
    Send(SCI_LINETRANSPOSE, 0, 0);
}

void jaeTextEditControl::lineReverse() {
    Send(SCI_LINEREVERSE, 0, 0);
}

void jaeTextEditControl::lineDuplicate() {
    Send(SCI_LINEDUPLICATE, 0, 0);
}

void jaeTextEditControl::lowerCase() {
    Send(SCI_LOWERCASE, 0, 0);
}

void jaeTextEditControl::upperCase() {
    Send(SCI_UPPERCASE, 0, 0);
}

void jaeTextEditControl::lineScrollDown() {
    Send(SCI_LINESCROLLDOWN, 0, 0);
}

void jaeTextEditControl::lineScrollUp() {
    Send(SCI_LINESCROLLUP, 0, 0);
}

void jaeTextEditControl::deleteBackNotLine() {
    Send(SCI_DELETEBACKNOTLINE, 0, 0);
}

void jaeTextEditControl::homeDisplay() {
    Send(SCI_HOMEDISPLAY, 0, 0);
}

void jaeTextEditControl::homeDisplayExtend() {
    Send(SCI_HOMEDISPLAYEXTEND, 0, 0);
}

void jaeTextEditControl::lineEndDisplay() {
    Send(SCI_LINEENDDISPLAY, 0, 0);
}

void jaeTextEditControl::lineEndDisplayExtend() {
    Send(SCI_LINEENDDISPLAYEXTEND, 0, 0);
}

void jaeTextEditControl::homeWrap() {
    Send(SCI_HOMEWRAP, 0, 0);
}

void jaeTextEditControl::homeWrapExtend() {
    Send(SCI_HOMEWRAPEXTEND, 0, 0);
}

void jaeTextEditControl::lineEndWrap() {
    Send(SCI_LINEENDWRAP, 0, 0);
}

void jaeTextEditControl::lineEndWrapExtend() {
    Send(SCI_LINEENDWRAPEXTEND, 0, 0);
}

void jaeTextEditControl::vCHomeWrap() {
    Send(SCI_VCHOMEWRAP, 0, 0);
}

void jaeTextEditControl::vCHomeWrapExtend() {
    Send(SCI_VCHOMEWRAPEXTEND, 0, 0);
}

void jaeTextEditControl::lineCopy() {
    Send(SCI_LINECOPY, 0, 0);
}

void jaeTextEditControl::moveCaretInsideView() {
    Send(SCI_MOVECARETINSIDEVIEW, 0, 0);
}

auto  jaeTextEditControl::lineLength(sptr_t line) -> sptr_t {
    return Send(SCI_LINELENGTH, line, 0);
}

void jaeTextEditControl::braceHighlight(sptr_t posA, sptr_t posB) {
    Send(SCI_BRACEHIGHLIGHT, posA, posB);
}

void jaeTextEditControl::braceHighlightIndicator(bool useSetting, sptr_t indicator) {
    Send(SCI_BRACEHIGHLIGHTINDICATOR, useSetting, indicator);
}

void jaeTextEditControl::braceBadLight(sptr_t pos) {
    Send(SCI_BRACEBADLIGHT, pos, 0);
}

void jaeTextEditControl::braceBadLightIndicator(bool useSetting, sptr_t indicator) {
    Send(SCI_BRACEBADLIGHTINDICATOR, useSetting, indicator);
}

auto  jaeTextEditControl::braceMatch(sptr_t pos, sptr_t maxReStyle) -> sptr_t {
    return Send(SCI_BRACEMATCH, pos, maxReStyle);
}

auto  jaeTextEditControl::braceMatchNext(sptr_t pos, sptr_t startPos) -> sptr_t {
    return Send(SCI_BRACEMATCHNEXT, pos, startPos);
}

auto  jaeTextEditControl::viewEOL() const -> bool {
    return Send(SCI_GETVIEWEOL, 0, 0);
}

void jaeTextEditControl::setViewEOL(bool visible) {
    Send(SCI_SETVIEWEOL, visible, 0);
}

auto  jaeTextEditControl::docPointer() const -> sptr_t {
    return Send(SCI_GETDOCPOINTER, 0, 0);
}

void jaeTextEditControl::setDocPointer(sptr_t doc) {
    Send(SCI_SETDOCPOINTER, 0, doc);
}

void jaeTextEditControl::setModEventMask(sptr_t eventMask) {
    Send(SCI_SETMODEVENTMASK, eventMask, 0);
}

auto  jaeTextEditControl::edgeColumn() const -> sptr_t {
    return Send(SCI_GETEDGECOLUMN, 0, 0);
}

void jaeTextEditControl::setEdgeColumn(sptr_t column) {
    Send(SCI_SETEDGECOLUMN, column, 0);
}

auto  jaeTextEditControl::edgeMode() const -> sptr_t {
    return Send(SCI_GETEDGEMODE, 0, 0);
}

void jaeTextEditControl::setEdgeMode(sptr_t edgeMode) {
    Send(SCI_SETEDGEMODE, edgeMode, 0);
}

auto  jaeTextEditControl::edgeColour() const -> sptr_t {
    return Send(SCI_GETEDGECOLOUR, 0, 0);
}

void jaeTextEditControl::setEdgeColour(sptr_t edgeColour) {
    Send(SCI_SETEDGECOLOUR, edgeColour, 0);
}

void jaeTextEditControl::multiEdgeAddLine(sptr_t column, sptr_t edgeColour) {
    Send(SCI_MULTIEDGEADDLINE, column, edgeColour);
}

void jaeTextEditControl::multiEdgeClearAll() {
    Send(SCI_MULTIEDGECLEARALL, 0, 0);
}

auto  jaeTextEditControl::multiEdgeColumn(sptr_t which) const -> sptr_t {
    return Send(SCI_GETMULTIEDGECOLUMN, which, 0);
}

void jaeTextEditControl::searchAnchor() {
    Send(SCI_SEARCHANCHOR, 0, 0);
}

auto  jaeTextEditControl::searchNext(sptr_t searchFlags, const char * text) -> sptr_t {
    return Send(SCI_SEARCHNEXT, searchFlags, (sptr_t)text);
}

auto  jaeTextEditControl::searchPrev(sptr_t searchFlags, const char * text) -> sptr_t {
    return Send(SCI_SEARCHPREV, searchFlags, (sptr_t)text);
}

auto  jaeTextEditControl::linesOnScreen() const -> sptr_t {
    return Send(SCI_LINESONSCREEN, 0, 0);
}

void jaeTextEditControl::usePopUp(sptr_t popUpMode) {
    Send(SCI_USEPOPUP, popUpMode, 0);
}

auto  jaeTextEditControl::selectionIsRectangle() const -> bool {
    return Send(SCI_SELECTIONISRECTANGLE, 0, 0);
}

void jaeTextEditControl::setZoom(sptr_t zoomInPoints) {
    Send(SCI_SETZOOM, zoomInPoints, 0);
}

auto  jaeTextEditControl::zoom() const -> sptr_t {
    return Send(SCI_GETZOOM, 0, 0);
}

auto  jaeTextEditControl::createDocument(sptr_t bytes, sptr_t documentOptions) -> sptr_t {
    return Send(SCI_CREATEDOCUMENT, bytes, documentOptions);
}

void jaeTextEditControl::addRefDocument(sptr_t doc) {
    Send(SCI_ADDREFDOCUMENT, 0, doc);
}

void jaeTextEditControl::releaseDocument(sptr_t doc) {
    Send(SCI_RELEASEDOCUMENT, 0, doc);
}

auto  jaeTextEditControl::documentOptions() const -> sptr_t {
    return Send(SCI_GETDOCUMENTOPTIONS, 0, 0);
}

auto  jaeTextEditControl::modEventMask() const -> sptr_t {
    return Send(SCI_GETMODEVENTMASK, 0, 0);
}

void jaeTextEditControl::setCommandEvents(bool commandEvents) {
    Send(SCI_SETCOMMANDEVENTS, commandEvents, 0);
}

auto  jaeTextEditControl::commandEvents() const -> bool {
    return Send(SCI_GETCOMMANDEVENTS, 0, 0);
}

void jaeTextEditControl::setFocus(bool focus) {
    Send(SCI_SETFOCUS, focus, 0);
}

auto  jaeTextEditControl::focus() const -> bool {
    return Send(SCI_GETFOCUS, 0, 0);
}

void jaeTextEditControl::setStatus(sptr_t status) {
    Send(SCI_SETSTATUS, status, 0);
}

auto  jaeTextEditControl::status() const -> sptr_t {
    return Send(SCI_GETSTATUS, 0, 0);
}

void jaeTextEditControl::setMouseDownCaptures(bool captures) {
    Send(SCI_SETMOUSEDOWNCAPTURES, captures, 0);
}

auto  jaeTextEditControl::mouseDownCaptures() const -> bool {
    return Send(SCI_GETMOUSEDOWNCAPTURES, 0, 0);
}

void jaeTextEditControl::setMouseWheelCaptures(bool captures) {
    Send(SCI_SETMOUSEWHEELCAPTURES, captures, 0);
}

auto  jaeTextEditControl::mouseWheelCaptures() const -> bool {
    return Send(SCI_GETMOUSEWHEELCAPTURES, 0, 0);
}

void jaeTextEditControl::setCursor(sptr_t cursorType) {
    Send(SCI_SETCURSOR, cursorType, 0);
}

auto  jaeTextEditControl::cursor() const -> sptr_t {
    return Send(SCI_GETCURSOR, 0, 0);
}

void jaeTextEditControl::setControlCharSymbol(sptr_t symbol) {
    Send(SCI_SETCONTROLCHARSYMBOL, symbol, 0);
}

auto  jaeTextEditControl::controlCharSymbol() const -> sptr_t {
    return Send(SCI_GETCONTROLCHARSYMBOL, 0, 0);
}

void jaeTextEditControl::wordPartLeft() {
    Send(SCI_WORDPARTLEFT, 0, 0);
}

void jaeTextEditControl::wordPartLeftExtend() {
    Send(SCI_WORDPARTLEFTEXTEND, 0, 0);
}

void jaeTextEditControl::wordPartRight() {
    Send(SCI_WORDPARTRIGHT, 0, 0);
}

void jaeTextEditControl::wordPartRightExtend() {
    Send(SCI_WORDPARTRIGHTEXTEND, 0, 0);
}

void jaeTextEditControl::setVisiblePolicy(sptr_t visiblePolicy, sptr_t visibleSlop) {
    Send(SCI_SETVISIBLEPOLICY, visiblePolicy, visibleSlop);
}

void jaeTextEditControl::delLineLeft() {
    Send(SCI_DELLINELEFT, 0, 0);
}

void jaeTextEditControl::delLineRight() {
    Send(SCI_DELLINERIGHT, 0, 0);
}

void jaeTextEditControl::setXOffset(sptr_t xOffset) {
    Send(SCI_SETXOFFSET, xOffset, 0);
}

auto  jaeTextEditControl::xOffset() const -> sptr_t {
    return Send(SCI_GETXOFFSET, 0, 0);
}

void jaeTextEditControl::chooseCaretX() {
    Send(SCI_CHOOSECARETX, 0, 0);
}

void jaeTextEditControl::grabFocus() {
    Send(SCI_GRABFOCUS, 0, 0);
}

void jaeTextEditControl::setXCaretPolicy(sptr_t caretPolicy, sptr_t caretSlop) {
    Send(SCI_SETXCARETPOLICY, caretPolicy, caretSlop);
}

void jaeTextEditControl::setYCaretPolicy(sptr_t caretPolicy, sptr_t caretSlop) {
    Send(SCI_SETYCARETPOLICY, caretPolicy, caretSlop);
}

void jaeTextEditControl::setPrintWrapMode(sptr_t wrapMode) {
    Send(SCI_SETPRINTWRAPMODE, wrapMode, 0);
}

auto  jaeTextEditControl::printWrapMode() const -> sptr_t {
    return Send(SCI_GETPRINTWRAPMODE, 0, 0);
}

void jaeTextEditControl::setHotspotActiveFore(bool useSetting, sptr_t fore) {
    Send(SCI_SETHOTSPOTACTIVEFORE, useSetting, fore);
}

auto  jaeTextEditControl::hotspotActiveFore() const -> sptr_t {
    return Send(SCI_GETHOTSPOTACTIVEFORE, 0, 0);
}

void jaeTextEditControl::setHotspotActiveBack(bool useSetting, sptr_t back) {
    Send(SCI_SETHOTSPOTACTIVEBACK, useSetting, back);
}

auto  jaeTextEditControl::hotspotActiveBack() const -> sptr_t {
    return Send(SCI_GETHOTSPOTACTIVEBACK, 0, 0);
}

void jaeTextEditControl::setHotspotActiveUnderline(bool underline) {
    Send(SCI_SETHOTSPOTACTIVEUNDERLINE, underline, 0);
}

auto  jaeTextEditControl::hotspotActiveUnderline() const -> bool {
    return Send(SCI_GETHOTSPOTACTIVEUNDERLINE, 0, 0);
}

void jaeTextEditControl::setHotspotSingleLine(bool singleLine) {
    Send(SCI_SETHOTSPOTSINGLELINE, singleLine, 0);
}

auto  jaeTextEditControl::hotspotSingleLine() const -> bool {
    return Send(SCI_GETHOTSPOTSINGLELINE, 0, 0);
}

void jaeTextEditControl::paraDown() {
    Send(SCI_PARADOWN, 0, 0);
}

void jaeTextEditControl::paraDownExtend() {
    Send(SCI_PARADOWNEXTEND, 0, 0);
}

void jaeTextEditControl::paraUp() {
    Send(SCI_PARAUP, 0, 0);
}

void jaeTextEditControl::paraUpExtend() {
    Send(SCI_PARAUPEXTEND, 0, 0);
}

auto  jaeTextEditControl::positionBefore(sptr_t pos) -> sptr_t {
    return Send(SCI_POSITIONBEFORE, pos, 0);
}

auto  jaeTextEditControl::positionAfter(sptr_t pos) -> sptr_t {
    return Send(SCI_POSITIONAFTER, pos, 0);
}

auto  jaeTextEditControl::positionRelative(sptr_t pos, sptr_t relative) -> sptr_t {
    return Send(SCI_POSITIONRELATIVE, pos, relative);
}

auto  jaeTextEditControl::positionRelativeCodeUnits(sptr_t pos, sptr_t relative) -> sptr_t {
    return Send(SCI_POSITIONRELATIVECODEUNITS, pos, relative);
}

void jaeTextEditControl::copyRange(sptr_t start, sptr_t end) {
    Send(SCI_COPYRANGE, start, end);
}

void jaeTextEditControl::copyText(sptr_t length, const char * text) {
    Send(SCI_COPYTEXT, length, (sptr_t)text);
}

void jaeTextEditControl::setSelectionMode(sptr_t selectionMode) {
    Send(SCI_SETSELECTIONMODE, selectionMode, 0);
}

auto  jaeTextEditControl::selectionMode() const -> sptr_t {
    return Send(SCI_GETSELECTIONMODE, 0, 0);
}

auto  jaeTextEditControl::moveExtendsSelection() const -> bool {
    return Send(SCI_GETMOVEEXTENDSSELECTION, 0, 0);
}

auto  jaeTextEditControl::getLineSelStartPosition(sptr_t line) -> sptr_t {
    return Send(SCI_GETLINESELSTARTPOSITION, line, 0);
}

auto  jaeTextEditControl::getLineSelEndPosition(sptr_t line) -> sptr_t {
    return Send(SCI_GETLINESELENDPOSITION, line, 0);
}

void jaeTextEditControl::lineDownRectExtend() {
    Send(SCI_LINEDOWNRECTEXTEND, 0, 0);
}

void jaeTextEditControl::lineUpRectExtend() {
    Send(SCI_LINEUPRECTEXTEND, 0, 0);
}

void jaeTextEditControl::charLeftRectExtend() {
    Send(SCI_CHARLEFTRECTEXTEND, 0, 0);
}

void jaeTextEditControl::charRightRectExtend() {
    Send(SCI_CHARRIGHTRECTEXTEND, 0, 0);
}

void jaeTextEditControl::homeRectExtend() {
    Send(SCI_HOMERECTEXTEND, 0, 0);
}

void jaeTextEditControl::vCHomeRectExtend() {
    Send(SCI_VCHOMERECTEXTEND, 0, 0);
}

void jaeTextEditControl::lineEndRectExtend() {
    Send(SCI_LINEENDRECTEXTEND, 0, 0);
}

void jaeTextEditControl::pageUpRectExtend() {
    Send(SCI_PAGEUPRECTEXTEND, 0, 0);
}

void jaeTextEditControl::pageDownRectExtend() {
    Send(SCI_PAGEDOWNRECTEXTEND, 0, 0);
}

void jaeTextEditControl::stutteredPageUp() {
    Send(SCI_STUTTEREDPAGEUP, 0, 0);
}

void jaeTextEditControl::stutteredPageUpExtend() {
    Send(SCI_STUTTEREDPAGEUPEXTEND, 0, 0);
}

void jaeTextEditControl::stutteredPageDown() {
    Send(SCI_STUTTEREDPAGEDOWN, 0, 0);
}

void jaeTextEditControl::stutteredPageDownExtend() {
    Send(SCI_STUTTEREDPAGEDOWNEXTEND, 0, 0);
}

void jaeTextEditControl::wordLeftEnd() {
    Send(SCI_WORDLEFTEND, 0, 0);
}

void jaeTextEditControl::wordLeftEndExtend() {
    Send(SCI_WORDLEFTENDEXTEND, 0, 0);
}

void jaeTextEditControl::wordRightEnd() {
    Send(SCI_WORDRIGHTEND, 0, 0);
}

void jaeTextEditControl::wordRightEndExtend() {
    Send(SCI_WORDRIGHTENDEXTEND, 0, 0);
}

void jaeTextEditControl::setWhitespaceChars(const char * characters) {
    Send(SCI_SETWHITESPACECHARS, 0, (sptr_t)characters);
}

auto  jaeTextEditControl::whitespaceChars() const -> wxCharBuffer {
    return TextReturner(SCI_GETWHITESPACECHARS, 0);
}

void jaeTextEditControl::setPunctuationChars(const char * characters) {
    Send(SCI_SETPUNCTUATIONCHARS, 0, (sptr_t)characters);
}

auto  jaeTextEditControl::punctuationChars() const -> wxCharBuffer {
    return TextReturner(SCI_GETPUNCTUATIONCHARS, 0);
}

void jaeTextEditControl::setCharsDefault() {
    Send(SCI_SETCHARSDEFAULT, 0, 0);
}

auto  jaeTextEditControl::autoCCurrent() const -> sptr_t {
    return Send(SCI_AUTOCGETCURRENT, 0, 0);
}

auto  jaeTextEditControl::autoCCurrentText() const -> wxCharBuffer {
    return TextReturner(SCI_AUTOCGETCURRENTTEXT, 0);
}

void jaeTextEditControl::autoCSetCaseInsensitiveBehaviour(sptr_t behaviour) {
    Send(SCI_AUTOCSETCASEINSENSITIVEBEHAVIOUR, behaviour, 0);
}

auto  jaeTextEditControl::autoCCaseInsensitiveBehaviour() const -> sptr_t {
    return Send(SCI_AUTOCGETCASEINSENSITIVEBEHAVIOUR, 0, 0);
}

void jaeTextEditControl::autoCSetMulti(sptr_t multi) {
    Send(SCI_AUTOCSETMULTI, multi, 0);
}

auto  jaeTextEditControl::autoCMulti() const -> sptr_t {
    return Send(SCI_AUTOCGETMULTI, 0, 0);
}

void jaeTextEditControl::autoCSetOrder(sptr_t order) {
    Send(SCI_AUTOCSETORDER, order, 0);
}

auto  jaeTextEditControl::autoCOrder() const -> sptr_t {
    return Send(SCI_AUTOCGETORDER, 0, 0);
}

void jaeTextEditControl::allocate(sptr_t bytes) {
    Send(SCI_ALLOCATE, bytes, 0);
}

auto  jaeTextEditControl::targetAsUTF8() -> wxCharBuffer {
    return TextReturner(SCI_TARGETASUTF8, 0);
}

void jaeTextEditControl::setLengthForEncode(sptr_t bytes) {
    Send(SCI_SETLENGTHFORENCODE, bytes, 0);
}

auto  jaeTextEditControl::encodedFromUTF8(const char * utf8) -> wxCharBuffer {
    return TextReturner(SCI_ENCODEDFROMUTF8, (sptr_t)utf8);
}

auto  jaeTextEditControl::findColumn(sptr_t line, sptr_t column) -> sptr_t {
    return Send(SCI_FINDCOLUMN, line, column);
}

auto  jaeTextEditControl::caretSticky() const -> sptr_t {
    return Send(SCI_GETCARETSTICKY, 0, 0);
}

void jaeTextEditControl::setCaretSticky(sptr_t useCaretStickyBehaviour) {
    Send(SCI_SETCARETSTICKY, useCaretStickyBehaviour, 0);
}

void jaeTextEditControl::toggleCaretSticky() {
    Send(SCI_TOGGLECARETSTICKY, 0, 0);
}

void jaeTextEditControl::setPasteConvertEndings(bool convert) {
    Send(SCI_SETPASTECONVERTENDINGS, convert, 0);
}

auto  jaeTextEditControl::pasteConvertEndings() const -> bool {
    return Send(SCI_GETPASTECONVERTENDINGS, 0, 0);
}

void jaeTextEditControl::replaceRectangular(sptr_t length, const char * text) {
    Send(SCI_REPLACERECTANGULAR, length, (sptr_t)text);
}

void jaeTextEditControl::selectionDuplicate() {
    Send(SCI_SELECTIONDUPLICATE, 0, 0);
}

void jaeTextEditControl::setCaretLineBackAlpha(sptr_t alpha) {
    Send(SCI_SETCARETLINEBACKALPHA, alpha, 0);
}

auto  jaeTextEditControl::caretLineBackAlpha() const -> sptr_t {
    return Send(SCI_GETCARETLINEBACKALPHA, 0, 0);
}

void jaeTextEditControl::setCaretStyle(sptr_t caretStyle) {
    Send(SCI_SETCARETSTYLE, caretStyle, 0);
}

auto  jaeTextEditControl::caretStyle() const -> sptr_t {
    return Send(SCI_GETCARETSTYLE, 0, 0);
}

void jaeTextEditControl::setIndicatorCurrent(sptr_t indicator) {
    Send(SCI_SETINDICATORCURRENT, indicator, 0);
}

auto  jaeTextEditControl::indicatorCurrent() const -> sptr_t {
    return Send(SCI_GETINDICATORCURRENT, 0, 0);
}

void jaeTextEditControl::setIndicatorValue(sptr_t value) {
    Send(SCI_SETINDICATORVALUE, value, 0);
}

auto  jaeTextEditControl::indicatorValue() const -> sptr_t {
    return Send(SCI_GETINDICATORVALUE, 0, 0);
}

void jaeTextEditControl::indicatorFillRange(sptr_t start, sptr_t lengthFill) {
    Send(SCI_INDICATORFILLRANGE, start, lengthFill);
}

void jaeTextEditControl::indicatorClearRange(sptr_t start, sptr_t lengthClear) {
    Send(SCI_INDICATORCLEARRANGE, start, lengthClear);
}

auto  jaeTextEditControl::indicatorAllOnFor(sptr_t pos) -> sptr_t {
    return Send(SCI_INDICATORALLONFOR, pos, 0);
}

auto  jaeTextEditControl::indicatorValueAt(sptr_t indicator, sptr_t pos) -> sptr_t {
    return Send(SCI_INDICATORVALUEAT, indicator, pos);
}

auto  jaeTextEditControl::indicatorStart(sptr_t indicator, sptr_t pos) -> sptr_t {
    return Send(SCI_INDICATORSTART, indicator, pos);
}

auto  jaeTextEditControl::indicatorEnd(sptr_t indicator, sptr_t pos) -> sptr_t {
    return Send(SCI_INDICATOREND, indicator, pos);
}

void jaeTextEditControl::setPositionCache(sptr_t size) {
    Send(SCI_SETPOSITIONCACHE, size, 0);
}

auto  jaeTextEditControl::positionCache() const -> sptr_t {
    return Send(SCI_GETPOSITIONCACHE, 0, 0);
}

void jaeTextEditControl::copyAllowLine() {
    Send(SCI_COPYALLOWLINE, 0, 0);
}

auto  jaeTextEditControl::characterPointer() const -> sptr_t {
    return Send(SCI_GETCHARACTERPOINTER, 0, 0);
}

auto  jaeTextEditControl::rangePointer(sptr_t start, sptr_t lengthRange) const -> sptr_t {
    return Send(SCI_GETRANGEPOINTER, start, lengthRange);
}

auto  jaeTextEditControl::gapPosition() const -> sptr_t {
    return Send(SCI_GETGAPPOSITION, 0, 0);
}

void jaeTextEditControl::indicSetAlpha(sptr_t indicator, sptr_t alpha) {
    Send(SCI_INDICSETALPHA, indicator, alpha);
}

auto  jaeTextEditControl::indicAlpha(sptr_t indicator) const -> sptr_t {
    return Send(SCI_INDICGETALPHA, indicator, 0);
}

void jaeTextEditControl::indicSetOutlineAlpha(sptr_t indicator, sptr_t alpha) {
    Send(SCI_INDICSETOUTLINEALPHA, indicator, alpha);
}

auto  jaeTextEditControl::indicOutlineAlpha(sptr_t indicator) const -> sptr_t {
    return Send(SCI_INDICGETOUTLINEALPHA, indicator, 0);
}

void jaeTextEditControl::setExtraAscent(sptr_t extraAscent) {
    Send(SCI_SETEXTRAASCENT, extraAscent, 0);
}

auto  jaeTextEditControl::extraAscent() const -> sptr_t {
    return Send(SCI_GETEXTRAASCENT, 0, 0);
}

void jaeTextEditControl::setExtraDescent(sptr_t extraDescent) {
    Send(SCI_SETEXTRADESCENT, extraDescent, 0);
}

auto  jaeTextEditControl::extraDescent() const -> sptr_t {
    return Send(SCI_GETEXTRADESCENT, 0, 0);
}

auto  jaeTextEditControl::markerSymbolDefined(sptr_t markerNumber) -> sptr_t {
    return Send(SCI_MARKERSYMBOLDEFINED, markerNumber, 0);
}

void jaeTextEditControl::marginSetText(sptr_t line, const char * text) {
    Send(SCI_MARGINSETTEXT, line, (sptr_t)text);
}

auto  jaeTextEditControl::marginText(sptr_t line) const -> wxCharBuffer {
    return TextReturner(SCI_MARGINGETTEXT, line);
}

void jaeTextEditControl::marginSetStyle(sptr_t line, sptr_t style) {
    Send(SCI_MARGINSETSTYLE, line, style);
}

auto  jaeTextEditControl::marginStyle(sptr_t line) const -> sptr_t {
    return Send(SCI_MARGINGETSTYLE, line, 0);
}

void jaeTextEditControl::marginSetStyles(sptr_t line, const char * styles) {
    Send(SCI_MARGINSETSTYLES, line, (sptr_t)styles);
}

auto  jaeTextEditControl::marginStyles(sptr_t line) const -> wxCharBuffer {
    return TextReturner(SCI_MARGINGETSTYLES, line);
}

void jaeTextEditControl::marginTextClearAll() {
    Send(SCI_MARGINTEXTCLEARALL, 0, 0);
}

void jaeTextEditControl::marginSetStyleOffset(sptr_t style) {
    Send(SCI_MARGINSETSTYLEOFFSET, style, 0);
}

auto  jaeTextEditControl::marginStyleOffset() const -> sptr_t {
    return Send(SCI_MARGINGETSTYLEOFFSET, 0, 0);
}

void jaeTextEditControl::setMarginOptions(sptr_t marginOptions) {
    Send(SCI_SETMARGINOPTIONS, marginOptions, 0);
}

auto  jaeTextEditControl::marginOptions() const -> sptr_t {
    return Send(SCI_GETMARGINOPTIONS, 0, 0);
}

void jaeTextEditControl::annotationSetText(sptr_t line, const char * text) {
    Send(SCI_ANNOTATIONSETTEXT, line, (sptr_t)text);
}

auto  jaeTextEditControl::annotationText(sptr_t line) const -> wxCharBuffer {
    return TextReturner(SCI_ANNOTATIONGETTEXT, line);
}

void jaeTextEditControl::annotationSetStyle(sptr_t line, sptr_t style) {
    Send(SCI_ANNOTATIONSETSTYLE, line, style);
}

auto  jaeTextEditControl::annotationStyle(sptr_t line) const -> sptr_t {
    return Send(SCI_ANNOTATIONGETSTYLE, line, 0);
}

void jaeTextEditControl::annotationSetStyles(sptr_t line, const char * styles) {
    Send(SCI_ANNOTATIONSETSTYLES, line, (sptr_t)styles);
}

auto  jaeTextEditControl::annotationStyles(sptr_t line) const -> wxCharBuffer {
    return TextReturner(SCI_ANNOTATIONGETSTYLES, line);
}

auto  jaeTextEditControl::annotationLines(sptr_t line) const -> sptr_t {
    return Send(SCI_ANNOTATIONGETLINES, line, 0);
}

void jaeTextEditControl::annotationClearAll() {
    Send(SCI_ANNOTATIONCLEARALL, 0, 0);
}

void jaeTextEditControl::annotationSetVisible(sptr_t visible) {
    Send(SCI_ANNOTATIONSETVISIBLE, visible, 0);
}

auto  jaeTextEditControl::annotationVisible() const -> sptr_t {
    return Send(SCI_ANNOTATIONGETVISIBLE, 0, 0);
}

void jaeTextEditControl::annotationSetStyleOffset(sptr_t style) {
    Send(SCI_ANNOTATIONSETSTYLEOFFSET, style, 0);
}

auto  jaeTextEditControl::annotationStyleOffset() const -> sptr_t {
    return Send(SCI_ANNOTATIONGETSTYLEOFFSET, 0, 0);
}

void jaeTextEditControl::releaseAllExtendedStyles() {
    Send(SCI_RELEASEALLEXTENDEDSTYLES, 0, 0);
}

auto  jaeTextEditControl::allocateExtendedStyles(sptr_t numberStyles) -> sptr_t {
    return Send(SCI_ALLOCATEEXTENDEDSTYLES, numberStyles, 0);
}

void jaeTextEditControl::addUndoAction(sptr_t token, sptr_t flags) {
    Send(SCI_ADDUNDOACTION, token, flags);
}

auto  jaeTextEditControl::charPositionFromPoint(sptr_t x, sptr_t y) -> sptr_t {
    return Send(SCI_CHARPOSITIONFROMPOINT, x, y);
}

auto  jaeTextEditControl::charPositionFromPointClose(sptr_t x, sptr_t y) -> sptr_t {
    return Send(SCI_CHARPOSITIONFROMPOINTCLOSE, x, y);
}

void jaeTextEditControl::setMouseSelectionRectangularSwitch(bool mouseSelectionRectangularSwitch) {
    Send(SCI_SETMOUSESELECTIONRECTANGULARSWITCH, mouseSelectionRectangularSwitch, 0);
}

auto  jaeTextEditControl::mouseSelectionRectangularSwitch() const -> bool {
    return Send(SCI_GETMOUSESELECTIONRECTANGULARSWITCH, 0, 0);
}

void jaeTextEditControl::setMultipleSelection(bool multipleSelection) {
    Send(SCI_SETMULTIPLESELECTION, multipleSelection, 0);
}

auto  jaeTextEditControl::multipleSelection() const -> bool {
    return Send(SCI_GETMULTIPLESELECTION, 0, 0);
}

void jaeTextEditControl::setAdditionalSelectionTyping(bool additionalSelectionTyping) {
    Send(SCI_SETADDITIONALSELECTIONTYPING, additionalSelectionTyping, 0);
}

auto  jaeTextEditControl::additionalSelectionTyping() const -> bool {
    return Send(SCI_GETADDITIONALSELECTIONTYPING, 0, 0);
}

void jaeTextEditControl::setAdditionalCaretsBlink(bool additionalCaretsBlink) {
    Send(SCI_SETADDITIONALCARETSBLINK, additionalCaretsBlink, 0);
}

auto  jaeTextEditControl::additionalCaretsBlink() const -> bool {
    return Send(SCI_GETADDITIONALCARETSBLINK, 0, 0);
}

void jaeTextEditControl::setAdditionalCaretsVisible(bool additionalCaretsVisible) {
    Send(SCI_SETADDITIONALCARETSVISIBLE, additionalCaretsVisible, 0);
}

auto  jaeTextEditControl::additionalCaretsVisible() const -> bool {
    return Send(SCI_GETADDITIONALCARETSVISIBLE, 0, 0);
}

auto  jaeTextEditControl::selections() const -> sptr_t {
    return Send(SCI_GETSELECTIONS, 0, 0);
}

auto  jaeTextEditControl::selectionEmpty() const -> bool {
    return Send(SCI_GETSELECTIONEMPTY, 0, 0);
}

void jaeTextEditControl::clearSelections() {
    Send(SCI_CLEARSELECTIONS, 0, 0);
}

void jaeTextEditControl::setSelection(sptr_t caret, sptr_t anchor) {
    Send(SCI_SETSELECTION, caret, anchor);
}

void jaeTextEditControl::addSelection(sptr_t caret, sptr_t anchor) {
    Send(SCI_ADDSELECTION, caret, anchor);
}

void jaeTextEditControl::dropSelectionN(sptr_t selection) {
    Send(SCI_DROPSELECTIONN, selection, 0);
}

void jaeTextEditControl::setMainSelection(sptr_t selection) {
    Send(SCI_SETMAINSELECTION, selection, 0);
}

auto  jaeTextEditControl::mainSelection() const -> sptr_t {
    return Send(SCI_GETMAINSELECTION, 0, 0);
}

void jaeTextEditControl::setSelectionNCaret(sptr_t selection, sptr_t caret) {
    Send(SCI_SETSELECTIONNCARET, selection, caret);
}

auto  jaeTextEditControl::selectionNCaret(sptr_t selection) const -> sptr_t {
    return Send(SCI_GETSELECTIONNCARET, selection, 0);
}

void jaeTextEditControl::setSelectionNAnchor(sptr_t selection, sptr_t anchor) {
    Send(SCI_SETSELECTIONNANCHOR, selection, anchor);
}

auto  jaeTextEditControl::selectionNAnchor(sptr_t selection) const -> sptr_t {
    return Send(SCI_GETSELECTIONNANCHOR, selection, 0);
}

void jaeTextEditControl::setSelectionNCaretVirtualSpace(sptr_t selection, sptr_t space) {
    Send(SCI_SETSELECTIONNCARETVIRTUALSPACE, selection, space);
}

auto  jaeTextEditControl::selectionNCaretVirtualSpace(sptr_t selection) const -> sptr_t {
    return Send(SCI_GETSELECTIONNCARETVIRTUALSPACE, selection, 0);
}

void jaeTextEditControl::setSelectionNAnchorVirtualSpace(sptr_t selection, sptr_t space) {
    Send(SCI_SETSELECTIONNANCHORVIRTUALSPACE, selection, space);
}

auto  jaeTextEditControl::selectionNAnchorVirtualSpace(sptr_t selection) const -> sptr_t {
    return Send(SCI_GETSELECTIONNANCHORVIRTUALSPACE, selection, 0);
}

void jaeTextEditControl::setSelectionNStart(sptr_t selection, sptr_t anchor) {
    Send(SCI_SETSELECTIONNSTART, selection, anchor);
}

auto  jaeTextEditControl::selectionNStart(sptr_t selection) const -> sptr_t {
    return Send(SCI_GETSELECTIONNSTART, selection, 0);
}

auto  jaeTextEditControl::selectionNStartVirtualSpace(sptr_t selection) const -> sptr_t {
    return Send(SCI_GETSELECTIONNSTARTVIRTUALSPACE, selection, 0);
}

void jaeTextEditControl::setSelectionNEnd(sptr_t selection, sptr_t caret) {
    Send(SCI_SETSELECTIONNEND, selection, caret);
}

auto  jaeTextEditControl::selectionNEndVirtualSpace(sptr_t selection) const -> sptr_t {
    return Send(SCI_GETSELECTIONNENDVIRTUALSPACE, selection, 0);
}

auto  jaeTextEditControl::selectionNEnd(sptr_t selection) const -> sptr_t {
    return Send(SCI_GETSELECTIONNEND, selection, 0);
}

void jaeTextEditControl::setRectangularSelectionCaret(sptr_t caret) {
    Send(SCI_SETRECTANGULARSELECTIONCARET, caret, 0);
}

auto  jaeTextEditControl::rectangularSelectionCaret() const -> sptr_t {
    return Send(SCI_GETRECTANGULARSELECTIONCARET, 0, 0);
}

void jaeTextEditControl::setRectangularSelectionAnchor(sptr_t anchor) {
    Send(SCI_SETRECTANGULARSELECTIONANCHOR, anchor, 0);
}

auto  jaeTextEditControl::rectangularSelectionAnchor() const -> sptr_t {
    return Send(SCI_GETRECTANGULARSELECTIONANCHOR, 0, 0);
}

void jaeTextEditControl::setRectangularSelectionCaretVirtualSpace(sptr_t space) {
    Send(SCI_SETRECTANGULARSELECTIONCARETVIRTUALSPACE, space, 0);
}

auto  jaeTextEditControl::rectangularSelectionCaretVirtualSpace() const -> sptr_t {
    return Send(SCI_GETRECTANGULARSELECTIONCARETVIRTUALSPACE, 0, 0);
}

void jaeTextEditControl::setRectangularSelectionAnchorVirtualSpace(sptr_t space) {
    Send(SCI_SETRECTANGULARSELECTIONANCHORVIRTUALSPACE, space, 0);
}

auto  jaeTextEditControl::rectangularSelectionAnchorVirtualSpace() const -> sptr_t {
    return Send(SCI_GETRECTANGULARSELECTIONANCHORVIRTUALSPACE, 0, 0);
}

void jaeTextEditControl::setVirtualSpaceOptions(sptr_t virtualSpaceOptions) {
    Send(SCI_SETVIRTUALSPACEOPTIONS, virtualSpaceOptions, 0);
}

auto  jaeTextEditControl::virtualSpaceOptions() const -> sptr_t {
    return Send(SCI_GETVIRTUALSPACEOPTIONS, 0, 0);
}

void jaeTextEditControl::setRectangularSelectionModifier(sptr_t modifier) {
    Send(SCI_SETRECTANGULARSELECTIONMODIFIER, modifier, 0);
}

auto  jaeTextEditControl::rectangularSelectionModifier() const -> sptr_t {
    return Send(SCI_GETRECTANGULARSELECTIONMODIFIER, 0, 0);
}

void jaeTextEditControl::setAdditionalSelFore(sptr_t fore) {
    Send(SCI_SETADDITIONALSELFORE, fore, 0);
}

void jaeTextEditControl::setAdditionalSelBack(sptr_t back) {
    Send(SCI_SETADDITIONALSELBACK, back, 0);
}

void jaeTextEditControl::setAdditionalSelAlpha(sptr_t alpha) {
    Send(SCI_SETADDITIONALSELALPHA, alpha, 0);
}

auto  jaeTextEditControl::additionalSelAlpha() const -> sptr_t {
    return Send(SCI_GETADDITIONALSELALPHA, 0, 0);
}

void jaeTextEditControl::setAdditionalCaretFore(sptr_t fore) {
    Send(SCI_SETADDITIONALCARETFORE, fore, 0);
}

auto  jaeTextEditControl::additionalCaretFore() const -> sptr_t {
    return Send(SCI_GETADDITIONALCARETFORE, 0, 0);
}

void jaeTextEditControl::rotateSelection() {
    Send(SCI_ROTATESELECTION, 0, 0);
}

void jaeTextEditControl::swapMainAnchorCaret() {
    Send(SCI_SWAPMAINANCHORCARET, 0, 0);
}

void jaeTextEditControl::multipleSelectAddNext() {
    Send(SCI_MULTIPLESELECTADDNEXT, 0, 0);
}

void jaeTextEditControl::multipleSelectAddEach() {
    Send(SCI_MULTIPLESELECTADDEACH, 0, 0);
}

auto  jaeTextEditControl::changeLexerState(sptr_t start, sptr_t end) -> sptr_t {
    return Send(SCI_CHANGELEXERSTATE, start, end);
}

auto  jaeTextEditControl::contractedFoldNext(sptr_t lineStart) -> sptr_t {
    return Send(SCI_CONTRACTEDFOLDNEXT, lineStart, 0);
}

void jaeTextEditControl::verticalCentreCaret() {
    Send(SCI_VERTICALCENTRECARET, 0, 0);
}

void jaeTextEditControl::moveSelectedLinesUp() {
    Send(SCI_MOVESELECTEDLINESUP, 0, 0);
}

void jaeTextEditControl::moveSelectedLinesDown() {
    Send(SCI_MOVESELECTEDLINESDOWN, 0, 0);
}

void jaeTextEditControl::setIdentifier(sptr_t identifier) {
    Send(SCI_SETIDENTIFIER, identifier, 0);
}

auto  jaeTextEditControl::identifier() const -> sptr_t {
    return Send(SCI_GETIDENTIFIER, 0, 0);
}

void jaeTextEditControl::rGBAImageSetWidth(sptr_t width) {
    Send(SCI_RGBAIMAGESETWIDTH, width, 0);
}

void jaeTextEditControl::rGBAImageSetHeight(sptr_t height) {
    Send(SCI_RGBAIMAGESETHEIGHT, height, 0);
}

void jaeTextEditControl::rGBAImageSetScale(sptr_t scalePercent) {
    Send(SCI_RGBAIMAGESETSCALE, scalePercent, 0);
}

void jaeTextEditControl::markerDefineRGBAImage(sptr_t markerNumber, const char * pixels) {
    Send(SCI_MARKERDEFINERGBAIMAGE, markerNumber, (sptr_t)pixels);
}

void jaeTextEditControl::registerRGBAImage(sptr_t type, const char * pixels) {
    Send(SCI_REGISTERRGBAIMAGE, type, (sptr_t)pixels);
}

void jaeTextEditControl::scrollToStart() {
    Send(SCI_SCROLLTOSTART, 0, 0);
}

void jaeTextEditControl::scrollToEnd() {
    Send(SCI_SCROLLTOEND, 0, 0);
}

void jaeTextEditControl::setTechnology(sptr_t technology) {
    Send(SCI_SETTECHNOLOGY, technology, 0);
}

auto  jaeTextEditControl::technology() const -> sptr_t {
    return Send(SCI_GETTECHNOLOGY, 0, 0);
}

auto  jaeTextEditControl::createLoader(sptr_t bytes, sptr_t documentOptions) -> sptr_t {
    return Send(SCI_CREATELOADER, bytes, documentOptions);
}

void jaeTextEditControl::findIndicatorShow(sptr_t start, sptr_t end) {
    Send(SCI_FINDINDICATORSHOW, start, end);
}

void jaeTextEditControl::findIndicatorFlash(sptr_t start, sptr_t end) {
    Send(SCI_FINDINDICATORFLASH, start, end);
}

void jaeTextEditControl::findIndicatorHide() {
    Send(SCI_FINDINDICATORHIDE, 0, 0);
}

void jaeTextEditControl::vCHomeDisplay() {
    Send(SCI_VCHOMEDISPLAY, 0, 0);
}

void jaeTextEditControl::vCHomeDisplayExtend() {
    Send(SCI_VCHOMEDISPLAYEXTEND, 0, 0);
}

auto  jaeTextEditControl::caretLineVisibleAlways() const -> bool {
    return Send(SCI_GETCARETLINEVISIBLEALWAYS, 0, 0);
}

void jaeTextEditControl::setCaretLineVisibleAlways(bool alwaysVisible) {
    Send(SCI_SETCARETLINEVISIBLEALWAYS, alwaysVisible, 0);
}

void jaeTextEditControl::setLineEndTypesAllowed(sptr_t lineEndBitSet) {
    Send(SCI_SETLINEENDTYPESALLOWED, lineEndBitSet, 0);
}

auto  jaeTextEditControl::lineEndTypesAllowed() const -> sptr_t {
    return Send(SCI_GETLINEENDTYPESALLOWED, 0, 0);
}

auto  jaeTextEditControl::lineEndTypesActive() const -> sptr_t {
    return Send(SCI_GETLINEENDTYPESACTIVE, 0, 0);
}

void jaeTextEditControl::setRepresentation(const char * encodedCharacter, const char * representation) {
    Send(SCI_SETREPRESENTATION, (sptr_t)encodedCharacter, (sptr_t)representation);
}

auto  jaeTextEditControl::representation(const char * encodedCharacter) const -> wxCharBuffer {
    return TextReturner(SCI_GETREPRESENTATION, (sptr_t)encodedCharacter);
}

void jaeTextEditControl::clearRepresentation(const char * encodedCharacter) {
    Send(SCI_CLEARREPRESENTATION, (sptr_t)encodedCharacter, 0);
}

void jaeTextEditControl::clearAllRepresentations() {
    Send(SCI_CLEARALLREPRESENTATIONS, 0, 0);
}

void jaeTextEditControl::setRepresentationAppearance(const char * encodedCharacter, sptr_t appearance) {
    Send(SCI_SETREPRESENTATIONAPPEARANCE, (sptr_t)encodedCharacter, appearance);
}

auto  jaeTextEditControl::representationAppearance(const char * encodedCharacter) const -> sptr_t {
    return Send(SCI_GETREPRESENTATIONAPPEARANCE, (sptr_t)encodedCharacter, 0);
}

void jaeTextEditControl::setRepresentationColour(const char * encodedCharacter, sptr_t colour) {
    Send(SCI_SETREPRESENTATIONCOLOUR, (sptr_t)encodedCharacter, colour);
}

auto  jaeTextEditControl::representationColour(const char * encodedCharacter) const -> sptr_t {
    return Send(SCI_GETREPRESENTATIONCOLOUR, (sptr_t)encodedCharacter, 0);
}

void jaeTextEditControl::eOLAnnotationSetText(sptr_t line, const char * text) {
    Send(SCI_EOLANNOTATIONSETTEXT, line, (sptr_t)text);
}

auto  jaeTextEditControl::eOLAnnotationText(sptr_t line) const -> wxCharBuffer {
    return TextReturner(SCI_EOLANNOTATIONGETTEXT, line);
}

void jaeTextEditControl::eOLAnnotationSetStyle(sptr_t line, sptr_t style) {
    Send(SCI_EOLANNOTATIONSETSTYLE, line, style);
}

auto  jaeTextEditControl::eOLAnnotationStyle(sptr_t line) const -> sptr_t {
    return Send(SCI_EOLANNOTATIONGETSTYLE, line, 0);
}

void jaeTextEditControl::eOLAnnotationClearAll() {
    Send(SCI_EOLANNOTATIONCLEARALL, 0, 0);
}

void jaeTextEditControl::eOLAnnotationSetVisible(sptr_t visible) {
    Send(SCI_EOLANNOTATIONSETVISIBLE, visible, 0);
}

auto  jaeTextEditControl::eOLAnnotationVisible() const -> sptr_t {
    return Send(SCI_EOLANNOTATIONGETVISIBLE, 0, 0);
}

void jaeTextEditControl::eOLAnnotationSetStyleOffset(sptr_t style) {
    Send(SCI_EOLANNOTATIONSETSTYLEOFFSET, style, 0);
}

auto  jaeTextEditControl::eOLAnnotationStyleOffset() const -> sptr_t {
    return Send(SCI_EOLANNOTATIONGETSTYLEOFFSET, 0, 0);
}

auto  jaeTextEditControl::supportsFeature(sptr_t feature) const -> bool {
    return Send(SCI_SUPPORTSFEATURE, feature, 0);
}

auto  jaeTextEditControl::lineCharacterIndex() const -> sptr_t {
    return Send(SCI_GETLINECHARACTERINDEX, 0, 0);
}

void jaeTextEditControl::allocateLineCharacterIndex(sptr_t lineCharacterIndex) {
    Send(SCI_ALLOCATELINECHARACTERINDEX, lineCharacterIndex, 0);
}

void jaeTextEditControl::releaseLineCharacterIndex(sptr_t lineCharacterIndex) {
    Send(SCI_RELEASELINECHARACTERINDEX, lineCharacterIndex, 0);
}

auto  jaeTextEditControl::lineFromIndexPosition(sptr_t pos, sptr_t lineCharacterIndex) -> sptr_t {
    return Send(SCI_LINEFROMINDEXPOSITION, pos, lineCharacterIndex);
}

auto  jaeTextEditControl::indexPositionFromLine(sptr_t line, sptr_t lineCharacterIndex) -> sptr_t {
    return Send(SCI_INDEXPOSITIONFROMLINE, line, lineCharacterIndex);
}

void jaeTextEditControl::startRecord() {
    Send(SCI_STARTRECORD, 0, 0);
}

void jaeTextEditControl::stopRecord() {
    Send(SCI_STOPRECORD, 0, 0);
}

auto  jaeTextEditControl::lexer() const -> sptr_t {
    return Send(SCI_GETLEXER, 0, 0);
}

void jaeTextEditControl::colourise(sptr_t start, sptr_t end) {
    Send(SCI_COLOURISE, start, end);
}

void jaeTextEditControl::setProperty(const char * key, const char * value) {
    Send(SCI_SETPROPERTY, (sptr_t)key, (sptr_t)value);
}

void jaeTextEditControl::setKeyWords(sptr_t keyWordSet, const char * keyWords) {
    Send(SCI_SETKEYWORDS, keyWordSet, (sptr_t)keyWords);
}

auto  jaeTextEditControl::property(const char * key) const -> wxCharBuffer {
    return TextReturner(SCI_GETPROPERTY, (sptr_t)key);
}

auto  jaeTextEditControl::propertyExpanded(const char * key) const -> wxCharBuffer {
    return TextReturner(SCI_GETPROPERTYEXPANDED, (sptr_t)key);
}

auto  jaeTextEditControl::propertyInt(const char * key, sptr_t defaultValue) const -> sptr_t {
    return Send(SCI_GETPROPERTYINT, (sptr_t)key, defaultValue);
}

auto  jaeTextEditControl::lexerLanguage() const -> wxCharBuffer {
    return TextReturner(SCI_GETLEXERLANGUAGE, 0);
}

auto  jaeTextEditControl::privateLexerCall(sptr_t operation, sptr_t pointer) -> sptr_t {
    return Send(SCI_PRIVATELEXERCALL, operation, pointer);
}

auto  jaeTextEditControl::propertyNames() -> wxCharBuffer {
    return TextReturner(SCI_PROPERTYNAMES, 0);
}

auto  jaeTextEditControl::propertyType(const char * name) -> sptr_t {
    return Send(SCI_PROPERTYTYPE, (sptr_t)name, 0);
}

auto  jaeTextEditControl::describeProperty(const char * name) -> wxCharBuffer {
    return TextReturner(SCI_DESCRIBEPROPERTY, (sptr_t)name);
}

auto  jaeTextEditControl::describeKeyWordSets() -> wxCharBuffer {
    return TextReturner(SCI_DESCRIBEKEYWORDSETS, 0);
}

auto  jaeTextEditControl::lineEndTypesSupported() const -> sptr_t {
    return Send(SCI_GETLINEENDTYPESSUPPORTED, 0, 0);
}

auto  jaeTextEditControl::allocateSubStyles(sptr_t styleBase, sptr_t numberStyles) -> sptr_t {
    return Send(SCI_ALLOCATESUBSTYLES, styleBase, numberStyles);
}

auto  jaeTextEditControl::subStylesStart(sptr_t styleBase) const -> sptr_t {
    return Send(SCI_GETSUBSTYLESSTART, styleBase, 0);
}

auto  jaeTextEditControl::subStylesLength(sptr_t styleBase) const -> sptr_t {
    return Send(SCI_GETSUBSTYLESLENGTH, styleBase, 0);
}

auto  jaeTextEditControl::styleFromSubStyle(sptr_t subStyle) const -> sptr_t {
    return Send(SCI_GETSTYLEFROMSUBSTYLE, subStyle, 0);
}

auto  jaeTextEditControl::primaryStyleFromStyle(sptr_t style) const -> sptr_t {
    return Send(SCI_GETPRIMARYSTYLEFROMSTYLE, style, 0);
}

void jaeTextEditControl::freeSubStyles() {
    Send(SCI_FREESUBSTYLES, 0, 0);
}

void jaeTextEditControl::setIdentifiers(sptr_t style, const char * identifiers) {
    Send(SCI_SETIDENTIFIERS, style, (sptr_t)identifiers);
}

auto  jaeTextEditControl::distanceToSecondaryStyles() const -> sptr_t {
    return Send(SCI_DISTANCETOSECONDARYSTYLES, 0, 0);
}

auto  jaeTextEditControl::subStyleBases() const -> wxCharBuffer {
    return TextReturner(SCI_GETSUBSTYLEBASES, 0);
}

auto  jaeTextEditControl::namedStyles() const -> sptr_t {
    return Send(SCI_GETNAMEDSTYLES, 0, 0);
}

auto  jaeTextEditControl::nameOfStyle(sptr_t style) -> wxCharBuffer {
    return TextReturner(SCI_NAMEOFSTYLE, style);
}

auto  jaeTextEditControl::tagsOfStyle(sptr_t style) -> wxCharBuffer {
    return TextReturner(SCI_TAGSOFSTYLE, style);
}

auto  jaeTextEditControl::descriptionOfStyle(sptr_t style) -> wxCharBuffer {
    return TextReturner(SCI_DESCRIPTIONOFSTYLE, style);
}

void jaeTextEditControl::setILexer(sptr_t ilexer) {
    Send(SCI_SETILEXER, 0, ilexer);
}

auto  jaeTextEditControl::bidirectional() const -> sptr_t {
    return Send(SCI_GETBIDIRECTIONAL, 0, 0);
}

void jaeTextEditControl::setBidirectional(sptr_t bidirectional) {
    Send(SCI_SETBIDIRECTIONAL, bidirectional, 0);
}

/* --Autogenerated -- end of section automatically generated from Scintilla.iface */
